// Generated by supabase/typegen.py from the migrations — do not edit.
// Regenerate: supabase/test/run.sh fails when this is stale, and says how.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      attempts: {
        Row: {
          answered_at: string
          chosen_index: number
          chosen_role: string
          elapsed_ms: number | null
          id: number
          is_correct: boolean
          item_id: string
          peeked: boolean
          replays: number
          session_id: string | null
          stands_for: string | null
          think_ms: number | null
          user_id: string
        }
        Insert: {
          answered_at?: never
          chosen_index: number
          chosen_role?: never
          elapsed_ms?: number | null
          id?: never
          is_correct?: never
          item_id: string
          peeked?: boolean
          replays?: number
          session_id?: string | null
          stands_for?: string | null
          think_ms?: number | null
          user_id?: never
        }
        Update: {
          answered_at?: never
          chosen_index?: never
          chosen_role?: never
          elapsed_ms?: never
          id?: never
          is_correct?: never
          item_id?: never
          peeked?: never
          replays?: never
          session_id?: never
          stands_for?: never
          think_ms?: never
          user_id?: never
        }
        Relationships: [
          {
            foreignKeyName: "attempts_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attempts_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "practice_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attempts_stands_for_fkey"
            columns: ["stands_for"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
        ]
      }
      audio_clips: {
        Row: {
          audio_path: string | null
          channel: string
          created_at: string
          duration_ms: number | null
          id: string
          text: string
          voice: string
        }
        Insert: {
          audio_path?: never
          channel?: never
          created_at?: never
          duration_ms?: never
          id?: never
          text?: never
          voice?: never
        }
        Update: {
          audio_path?: never
          channel?: never
          created_at?: never
          duration_ms?: never
          id?: never
          text?: never
          voice?: never
        }
        Relationships: []
      }
      bundles: {
        Row: {
          generated_at: string
          generator_model: string
          id: string
          item_type: string
          level: string
          published_at: string
        }
        Insert: {
          generated_at?: never
          generator_model?: never
          id?: never
          item_type?: never
          level?: never
          published_at?: never
        }
        Update: {
          generated_at?: never
          generator_model?: never
          id?: never
          item_type?: never
          level?: never
          published_at?: never
        }
        Relationships: [
          {
            foreignKeyName: "bundles_item_type_fkey"
            columns: ["item_type"]
            isOneToOne: false
            referencedRelation: "item_types"
            referencedColumns: ["id"]
          },
        ]
      }
      entitlements: {
        Row: {
          external_id: string | null
          granted_at: string
          note: string | null
          product: string
          revoked_at: string | null
          source: string
          user_id: string
        }
        Insert: {
          external_id?: never
          granted_at?: never
          note?: never
          product?: never
          revoked_at?: never
          source?: never
          user_id?: never
        }
        Update: {
          external_id?: never
          granted_at?: never
          note?: never
          product?: never
          revoked_at?: never
          source?: never
          user_id?: never
        }
        Relationships: []
      }
      item_feedback: {
        Row: {
          created_at: string
          id: number
          item_id: string
          note: string
          reason: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: never
          item_id: string
          note?: string
          reason: string
          updated_at?: string
          user_id?: string
        }
        Update: {
          created_at?: string
          id?: never
          item_id?: string
          note?: string
          reason?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "item_feedback_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
        ]
      }
      item_options: {
        Row: {
          clip_id: string | null
          item_id: string
          position: number
          role: string
          text: string
          why: string
        }
        Insert: {
          clip_id?: never
          item_id?: never
          position?: never
          role?: never
          text?: never
          why?: never
        }
        Update: {
          clip_id?: never
          item_id?: never
          position?: never
          role?: never
          text?: never
          why?: never
        }
        Relationships: [
          {
            foreignKeyName: "item_options_clip_id_fkey"
            columns: ["clip_id"]
            isOneToOne: false
            referencedRelation: "audio_clips"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "item_options_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
        ]
      }
      item_types: {
        Row: {
          exam_questions: number
          id: string
          label_en: string
          label_ja: string
          needs_picture: boolean
          seconds_per_item: number | null
          section: string
          sort_order: number
          typical_chars: number | null
        }
        Insert: {
          exam_questions?: never
          id?: never
          label_en?: never
          label_ja?: never
          needs_picture?: never
          seconds_per_item?: never
          section?: never
          sort_order?: never
          typical_chars?: never
        }
        Update: {
          exam_questions?: never
          id?: never
          label_en?: never
          label_ja?: never
          needs_picture?: never
          seconds_per_item?: never
          section?: never
          sort_order?: never
          typical_chars?: never
        }
        Relationships: []
      }
      item_vetoes: {
        Row: {
          created_at: string
          item_id: string
          note: string
          user_id: string
        }
        Insert: {
          created_at?: never
          item_id?: never
          note?: never
          user_id?: never
        }
        Update: {
          created_at?: never
          item_id?: never
          note?: never
          user_id?: never
        }
        Relationships: [
          {
            foreignKeyName: "item_vetoes_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: true
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
        ]
      }
      items: {
        Row: {
          bundle_id: string
          channel: string | null
          correct_index: number
          created_at: string
          dialogue: Json
          documents: Json
          explanation_en: string
          explanation_ja: string
          function: string | null
          id: string
          is_published: boolean
          item_type: string
          level: string
          listener_role: string | null
          model_p_correct: number | null
          narration_clip_id: string | null
          relation: string | null
          scene_id: string | null
          seed_cell_id: string | null
          setting: string | null
          speaker_role: string | null
          stem: string
          topic: string
          vocab_notes: Json
        }
        Insert: {
          bundle_id?: never
          channel?: never
          correct_index?: never
          created_at?: never
          dialogue?: never
          documents?: never
          explanation_en?: never
          explanation_ja?: never
          function?: never
          id?: never
          is_published?: never
          item_type?: never
          level?: never
          listener_role?: never
          model_p_correct?: never
          narration_clip_id?: never
          relation?: never
          scene_id?: never
          seed_cell_id?: never
          setting?: never
          speaker_role?: never
          stem?: never
          topic?: never
          vocab_notes?: never
        }
        Update: {
          bundle_id?: never
          channel?: never
          correct_index?: never
          created_at?: never
          dialogue?: never
          documents?: never
          explanation_en?: never
          explanation_ja?: never
          function?: never
          id?: never
          is_published?: never
          item_type?: never
          level?: never
          listener_role?: never
          model_p_correct?: never
          narration_clip_id?: never
          relation?: never
          scene_id?: never
          seed_cell_id?: never
          setting?: never
          speaker_role?: never
          stem?: never
          topic?: never
          vocab_notes?: never
        }
        Relationships: [
          {
            foreignKeyName: "items_bundle_id_fkey"
            columns: ["bundle_id"]
            isOneToOne: false
            referencedRelation: "bundles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "items_correct_option_fk"
            columns: ["id", "correct_index"]
            isOneToOne: false
            referencedRelation: "item_options"
            referencedColumns: ["item_id", "position"]
          },
          {
            foreignKeyName: "items_item_type_fkey"
            columns: ["item_type"]
            isOneToOne: false
            referencedRelation: "item_types"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "items_narration_clip_id_fkey"
            columns: ["narration_clip_id"]
            isOneToOne: false
            referencedRelation: "audio_clips"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "items_scene_id_fkey"
            columns: ["scene_id"]
            isOneToOne: false
            referencedRelation: "scenes"
            referencedColumns: ["id"]
          },
        ]
      }
      practice_sessions: {
        Row: {
          finished_at: string | null
          id: string
          started_at: string
          user_id: string
        }
        Insert: {
          finished_at?: string | null
          id?: string
          started_at?: string
          user_id: string
        }
        Update: {
          finished_at?: string | null
          id?: string
          started_at?: string
          user_id?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          created_at: string
          daily_goal: number
          display_name: string | null
          exam_date: string | null
          id: string
          is_anonymous: boolean
          level_changed_at: string
          linked_at: string | null
          target_level: string
          timed_reading: boolean
          updated_at: string
        }
        Insert: {
          created_at?: never
          daily_goal?: never
          display_name?: never
          exam_date?: never
          id?: never
          is_anonymous?: never
          level_changed_at?: never
          linked_at?: never
          target_level?: never
          timed_reading?: never
          updated_at?: never
        }
        Update: {
          created_at?: never
          daily_goal?: number
          display_name?: string | null
          exam_date?: string | null
          id?: never
          is_anonymous?: never
          level_changed_at?: never
          linked_at?: never
          target_level?: never
          timed_reading?: boolean
          updated_at?: never
        }
        Relationships: []
      }
      review_notes: {
        Row: {
          added_at: string
          item_id: string
          note: string
          user_id: string
        }
        Insert: {
          added_at?: string
          item_id: string
          note?: string
          user_id: string
        }
        Update: {
          added_at?: string
          item_id?: string
          note?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "review_notes_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
        ]
      }
      review_schedule: {
        Row: {
          due_at: string
          item_id: string
          last_at: string
          missed: boolean
          step: number
          trap: string | null
          user_id: string
        }
        Insert: {
          due_at?: never
          item_id?: never
          last_at?: never
          missed?: never
          step?: never
          trap?: never
          user_id?: never
        }
        Update: {
          due_at?: never
          item_id?: never
          last_at?: never
          missed?: never
          step?: never
          trap?: never
          user_id?: never
        }
        Relationships: [
          {
            foreignKeyName: "review_schedule_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
        ]
      }
      scenes: {
        Row: {
          id: string
          image_path: string | null
          label_ja: string
          updated_at: string
        }
        Insert: {
          id?: never
          image_path?: never
          label_ja?: never
          updated_at?: never
        }
        Update: {
          id?: never
          image_path?: never
          label_ja?: never
          updated_at?: never
        }
        Relationships: []
      }
      section_levels: {
        Row: {
          changed_at: string
          level: string
          moves: number
          section: string
          user_id: string
        }
        Insert: {
          changed_at?: never
          level?: never
          moves?: never
          section?: never
          user_id?: never
        }
        Update: {
          changed_at?: never
          level?: never
          moves?: never
          section?: never
          user_id?: never
        }
        Relationships: []
      }
    }
    Views: {
      v_item_difficulty: {
        Row: {
          item_id: string | null
          p_correct: number | null
        }
        Relationships: []
      }
      v_my_daily: {
        Row: {
          answered: number | null
          correct: number | null
          day: string | null
        }
        Relationships: []
      }
      v_my_day: {
        Row: {
          answered_today: number | null
          goal: number | null
          goal_max: number | null
          left_today: number | null
          max_today: number | null
          unlimited: boolean | null
        }
        Relationships: []
      }
      v_my_levels: {
        Row: {
          changed_at: string | null
          level: string | null
          placed: boolean | null
          section: string | null
        }
        Relationships: []
      }
      v_my_review_load: {
        Row: {
          due_now: number | null
          next_due_at: string | null
          tracked: number | null
        }
        Relationships: []
      }
      v_my_role_traps: {
        Row: {
          last_chosen_at: string | null
          recent_met: number | null
          recent_times: number | null
          role: string | null
          times_chosen: number | null
          times_met: number | null
        }
        Relationships: []
      }
      v_my_tag_stats: {
        Row: {
          accuracy: number | null
          answered: number | null
          axis: string | null
          correct: number | null
          recent_accuracy: number | null
          recent_answered: number | null
          tag: string | null
        }
        Relationships: []
      }
      v_my_type_stats: {
        Row: {
          accuracy: number | null
          answered: number | null
          correct: number | null
          item_type: string | null
          label_ja: string | null
          last_answered_at: string | null
          recent_accuracy: number | null
          recent_answered: number | null
          section: string | null
          sort_order: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      daily_max: {
        Args: never
        Returns: number
      }
      is_tester: {
        Args: never
        Returns: boolean
      }
      is_unlimited: {
        Args: never
        Returns: boolean
      }
      level_evidence: {
        Args: {
          p_section: string
        }
        Returns: {
          answered: number
          correct: number
          level: string
          level_window: number
          since: string
        }[]
      }
      may_i_veto: {
        Args: never
        Returns: boolean
      }
      my_daily_max: {
        Args: never
        Returns: number
      }
      my_goal_max: {
        Args: never
        Returns: number
      }
      my_streak: {
        Args: never
        Returns: number
      }
      next_items: {
        Args: {
          p_limit?: number
        }
        Returns: {
          channel: string
          correct_index: number
          dialogue: Json
          documents: Json
          explanation_en: string
          explanation_ja: string
          id: string
          item_type: string
          lesson_trap: string
          level: string
          listener_role: string
          narration_clip_id: string
          narration_path: string
          options: Json
          scene_id: string
          scene_image_path: string
          seed_cell_id: string
          speaker_role: string
          stands_for: string
          stem: string
          times_seen: number
          topic: string
          vocab_notes: Json
        }[]
      }
      reset_my_progress: {
        Args: never
        Returns: Json
      }
      veto_item: {
        Args: {
          p_item_id: string
          p_note?: string
        }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database["public"]

export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Update"]
export type Views<T extends keyof PublicSchema["Views"]> = PublicSchema["Views"][T]["Row"]
export type Functions<T extends keyof PublicSchema["Functions"]> = PublicSchema["Functions"][T]
