-- The current definition of every function, view and trigger in
-- supabase/migrations/, each as the latest migration to touch it left it.
-- Generated by supabase/snapshot.py: do not edit, and do not apply —
-- the migrations are the schema; this is the schema made readable.
-- Tables are not here; supabase/test/run.sh applies and checks the whole.


-- ==== view v_item_difficulty — 20260917000100_testers_only.sql

create or replace view public.v_item_difficulty as
    select item_id, p_correct
      from public.item_stats
     where answered >= 8
       and p_correct is not null
       and (select public.is_tester());

comment on view public.v_item_difficulty is
    'Per-item success rate, over the first answers of at least eight different '
    'people. A property of the question, never of a person, and never displayed.';


-- ==== view v_my_daily — 20260913000300_stats_and_selection.sql

create view public.v_my_daily
with (security_invoker = on) as
select
    (a.answered_at at time zone 'Asia/Tokyo')::date       as day,
    count(*)                                              as answered,
    count(*) filter (where a.is_correct)                  as correct
from public.attempts a
group by 1;


-- ==== view v_my_day — 20260930000300_the_door_is_on_the_answer.sql

create or replace view public.v_my_day
with (security_invoker = on) as
with today as (
    select count(*)::int as answered
      from public.attempts a
     where a.user_id = (select auth.uid())
       and a.answered_at >= ((now() at time zone 'Asia/Tokyo')::date::timestamp
                             at time zone 'Asia/Tokyo')
)
select
    coalesce((select p.daily_goal from public.profiles p where p.id = (select auth.uid())), 10)
                                                        as goal,
    today.answered                                      as answered_today,
    (select public.is_unlimited())                      as unlimited,
    case when (select public.is_unlimited()) then null
         else (select public.my_daily_max()) end        as max_today,
    case when (select public.is_unlimited()) then null
         else greatest((select public.my_daily_max()) - today.answered, 0) end
                                                        as left_today,
    (select public.my_goal_max())                       as goal_max
from today;

comment on view public.v_my_day is
    'Today, for this learner: the goal, what is answered, whether the ceiling '
    'is lifted, the ceiling, how many more the queue will serve, and — for the '
    'one account that may size its own day — how large a set it may ask for. '
    'Days end at midnight in Japan, as the streak counts them.';


-- ==== view v_my_levels — 20260927000100_a_new_question_not_the_same_one.sql

create or replace view public.v_my_levels
with (security_invoker = on) as
select s.section,
       coalesce(sl.level, 'J2')       as level,
       coalesce(sl.changed_at, now()) as changed_at,
       coalesce(sl.moves, 0) > 0
       or (sl.level is not null
           and ev.level_window >= 5
           and ev.answered >= least(10, ev.level_window)) as placed
from (values ('choukai'), ('choudokkai'), ('dokkai')) as s(section)
left join public.section_levels sl
       on sl.user_id = (select auth.uid()) and sl.section = s.section
left join lateral public.level_evidence(s.section) ev on true;


-- ==== view v_my_review_load — 20260916000500_shared_bank_and_spacing.sql

create view public.v_my_review_load
with (security_invoker = on) as
select
    count(*) filter (where r.due_at <= now())::int as due_now,
    count(*)::int                                  as tracked,
    min(r.due_at) filter (where r.due_at > now())  as next_due_at
from public.review_schedule r;


-- ==== view v_my_role_traps — 20260927000100_a_new_question_not_the_same_one.sql

create or replace view public.v_my_role_traps
with (security_invoker = on) as
with caught as (
    select a.chosen_role                as role,
           count(*)                     as times_chosen,
           max(a.answered_at)           as last_chosen_at,
           count(*) filter (where a.answered_at >= now() - interval '30 days')::int
                                        as recent_times
      from public.attempts a
      join public.items i on i.id = a.item_id and i.is_published
     where not a.is_correct
     group by a.chosen_role
),
met as (
    select o.role,
           count(*)::int as times_met,
           count(*) filter (where a.answered_at >= now() - interval '30 days')::int
                         as recent_met
      from public.attempts a
      join public.items i on i.id = a.item_id and i.is_published
      join public.item_options o on o.item_id = a.item_id and o.position <> i.correct_index
     group by o.role
)
select c.role, c.times_chosen, c.last_chosen_at, c.recent_times,
       m.times_met, m.recent_met
  from caught c
  left join met m on m.role = c.role;


-- ==== view v_my_tag_stats — 20260918000100_queue_keeps_its_promises.sql

create or replace view public.v_my_tag_stats
with (security_invoker = on) as
with tagged as (
    select 'function' as axis, i.function as tag, a.is_correct, a.answered_at from public.attempts a join public.items i on i.id = a.item_id where i.function is not null
    union all
    select 'relation', i.relation, a.is_correct, a.answered_at from public.attempts a join public.items i on i.id = a.item_id where i.relation is not null
    union all
    select 'setting',  i.setting,  a.is_correct, a.answered_at from public.attempts a join public.items i on i.id = a.item_id where i.setting is not null
    union all
    select 'channel',  i.channel,  a.is_correct, a.answered_at from public.attempts a join public.items i on i.id = a.item_id where i.channel is not null
)
select
    axis,
    tag,
    count(*)                                   as answered,
    count(*) filter (where is_correct)         as correct,
    count(*) filter (where is_correct)::numeric / count(*) as accuracy,
    count(*) filter (where answered_at >= now() - interval '30 days')::int
                                               as recent_answered,
    (coalesce(sum(power(0.5, extract(epoch from now() - answered_at) / (30 * 86400)))
                  filter (where is_correct), 0)
     / nullif(sum(power(0.5, extract(epoch from now() - answered_at) / (30 * 86400))), 0)
    )::numeric                                 as recent_accuracy
from tagged
group by axis, tag;


-- ==== view v_my_type_stats — 20260918000100_queue_keeps_its_promises.sql

create or replace view public.v_my_type_stats
with (security_invoker = on) as
select
    t.id                                                as item_type,
    t.label_ja,
    t.section,
    t.sort_order,
    count(a.id)                                         as answered,
    count(a.id) filter (where a.is_correct)             as correct,
    case when count(a.id) > 0
         then count(a.id) filter (where a.is_correct)::numeric / count(a.id)
    end                                                 as accuracy,
    max(a.answered_at)                                  as last_answered_at,
    count(a.id) filter (where a.answered_at >= now() - interval '30 days')::int
                                                        as recent_answered,
    -- Null when nothing was answered (the denominator is null), 0 when it was
    -- all wrong (a filtered sum over no rows is null, hence the coalesce).
    (coalesce(sum(power(0.5, extract(epoch from now() - a.answered_at) / (30 * 86400)))
                  filter (where a.is_correct), 0)
     / nullif(sum(power(0.5, extract(epoch from now() - a.answered_at) / (30 * 86400))), 0)
    )::numeric                                          as recent_accuracy
from public.item_types t
left join public.items i on i.item_type = t.id
left join public.attempts a on a.item_id = i.id
group by t.id, t.label_ja, t.section, t.sort_order;


-- ==== function adjust_level — 20260927000100_a_new_question_not_the_same_one.sql

create or replace function public.adjust_level()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_section text;
    ev        record;
    v_next    text;
    v_overall text;
begin
    select it.section
      into v_section
      from public.items i
      join public.item_types it on it.id = i.item_type
     where i.id = new.item_id;
    if v_section is null then
        return new;
    end if;

    -- The very first answer seeds all three sections at once, as before, so a
    -- strong reader does not meet 聴解 already at J1.
    insert into public.section_levels (user_id, section, level)
    select new.user_id, s.section,
           coalesce((select p.target_level from public.profiles p where p.id = new.user_id), 'J2')
    from (values ('choukai'), ('choudokkai'), ('dokkai')) as s(section)
    on conflict (user_id, section) do nothing;

    select * into ev from public.level_evidence(v_section);

    if ev.level_window >= 5 and ev.answered >= ev.level_window then
        if ev.correct * 10 >= ev.level_window * 8 then
            v_next := case ev.level when 'J3' then 'J2' when 'J2' then 'J1' end;
        elsif ev.correct * 10 <= ev.level_window * 4 then
            v_next := case ev.level when 'J1' then 'J2' when 'J2' then 'J3' end;
        end if;
    end if;

    if v_next is not null
       and public.questions_left(new.user_id, v_section, v_next) < 5 then
        v_next := null;
    end if;

    if v_next is not null then
        update public.section_levels
           set level = v_next, changed_at = now(), moves = moves + 1
         where user_id = new.user_id and section = v_section;
    end if;

    -- `profiles.target_level` stays the one-line summary: the middle of the
    -- three. It decides nothing.
    select sl.level into v_overall
      from public.section_levels sl
     where sl.user_id = new.user_id
     order by case sl.level when 'J3' then 0 when 'J2' then 1 else 2 end
     offset 1 limit 1;

    if v_overall is not null then
        update public.profiles
           set target_level     = v_overall,
               level_changed_at = case when target_level is distinct from v_overall
                                       then now() else level_changed_at end,
               updated_at       = now()
         where id = new.user_id
           and target_level is distinct from v_overall;
    end if;
    return new;
end;
$$;

comment on function public.adjust_level is
    'Move the level of the section this answer belongs to, on level_evidence(): the '
    'latest unaided first attempts at that level, ten or twenty of them but never '
    'more than the level has questions for, and never fewer than five. Nobody is '
    'moved into a level with fewer than five questions left to meet.';


-- ==== function daily_max — 20260918000200_ten_a_day_and_a_door.sql

create or replace function public.daily_max()
returns integer
language sql
immutable
set search_path = ''
as $$ select 15; $$;

comment on function public.daily_max is
    'The most items anybody may answer in one Japanese calendar day. A constant, '
    'so the app and the queue read the same number.';


-- ==== function grade_attempt — 20260930000400_a_withdrawn_question_takes_no_answers.sql

create or replace function public.grade_attempt()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_role          text;
    v_correct_index smallint;
    v_type          text;
    v_function      text;
    v_day_start     timestamptz :=
        ((now() at time zone 'Asia/Tokyo')::date::timestamp at time zone 'Asia/Tokyo');
    v_today         integer;
begin
    new.user_id := (select auth.uid());
    if new.user_id is null then
        raise exception 'attempts require an authenticated session';
    end if;

    -- Only a privileged insert can name this column (see the grant in
    -- 20260927000100), so for the app it is always now().
    new.answered_at := coalesce(new.answered_at, now());

    -- The day's door, on the answer itself. Counted under a lock per learner,
    -- so two devices answering at once are counted one after the other.
    if new.answered_at >= v_day_start and not (select public.is_unlimited()) then
        perform pg_advisory_xact_lock(hashtextextended('attempts:' || new.user_id::text, 0));
        select count(*)::int
          into v_today
          from public.attempts a
         where a.user_id = new.user_id
           and a.answered_at >= v_day_start;
        if v_today >= (select public.my_daily_max()) then
            raise exception 'daily limit reached'
                using errcode = 'check_violation', hint = 'daily_limit_reached';
        end if;
    end if;

    -- The item still has to exist, and still be in the bank: a question that
    -- was withdrawn or vetoed takes no new answers. Its answer key is read here
    -- and not taken from the client — a timeout is graded, not merely accepted.
    select i.correct_index, i.item_type, i.function
      into v_correct_index, v_type, v_function
      from public.items i
     where i.id = new.item_id
       and i.is_published;

    if v_correct_index is null then
        raise exception 'no such item %', new.item_id
            using hint = 'item_unavailable';
    end if;

    if new.chosen_index = -1 then
        new.is_correct  := false;
        new.chosen_role := 'timed_out';
    else
        select o.role
          into v_role
          from public.item_options o
         where o.item_id = new.item_id
           and o.position = new.chosen_index;

        if v_role is null then
            raise exception 'no option % for item %', new.chosen_index, new.item_id;
        end if;

        new.is_correct  := (new.chosen_index = v_correct_index);
        new.chosen_role := v_role;
    end if;

    if new.stands_for is not null and (
           new.stands_for = new.item_id
           or exists (select 1 from public.attempts a
                       where a.user_id = new.user_id and a.item_id = new.item_id)
           or not exists (
                select 1
                  from public.review_schedule r
                  join public.items l on l.id = r.item_id
                 where r.user_id = new.user_id
                   and r.item_id = new.stands_for
                   and r.due_at <= now()
                   and l.item_type = v_type
                   and case when r.trap is not null then
                                exists (select 1 from public.item_options o
                                         where o.item_id = new.item_id
                                           and o.role = r.trap
                                           and o.position <> v_correct_index)
                            else l.function is null or l.function = v_function
                       end)
       ) then
        new.stands_for := null;
    end if;

    return new;
end;
$$;

comment on function public.grade_attempt is
    'Grades an answer from the item, never from the client. chosen_index -1 means '
    'the question clock ran out: wrong, with the role timed_out. A stands_for that '
    'the queue could not have served is cleared. An answer that would take today '
    'past my_daily_max() is refused (hint daily_limit_reached), unless the '
    'tester''s ceiling is lifted, and so is an answer to a question that is not '
    'published (hint item_unavailable).';


-- ==== function grant_entitlement — 20260915000400_entitlement_grants.sql

create or replace function public.grant_entitlement(
    p_user_id     uuid,
    p_product     text default 'ads_free',
    p_source      text default 'grant',
    p_external_id text default null,
    p_note        text default null
)
returns public.entitlements
language plpgsql
security definer
set search_path = ''
as $$
declare
    row public.entitlements;
begin
    insert into public.entitlements (user_id, product, source, external_id, note)
    values (p_user_id, p_product, p_source, p_external_id, p_note)
    on conflict (user_id, product) do update set
        source      = excluded.source,
        external_id = coalesce(excluded.external_id, public.entitlements.external_id),
        note        = coalesce(excluded.note, public.entitlements.note),
        -- Re-granting after a revocation restores it, which is what a
        -- re-purchase after a refund means.
        revoked_at  = null
    returning * into row;

    return row;
end;
$$;

comment on function public.grant_entitlement is
    'Grant an entitlement as the service role. Idempotent on (source, external_id) so a replayed purchase webhook is free.';


-- ==== function handle_new_user — 20260913000200_users.sql

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    insert into public.profiles (id, is_anonymous, linked_at)
    values (
        new.id,
        coalesce(new.is_anonymous, false),
        case when coalesce(new.is_anonymous, false) then null else now() end
    )
    on conflict (id) do nothing;
    return new;
end;
$$;


-- ==== function is_tester — 20260917000100_testers_only.sql

create or replace function public.is_tester()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select not coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false)
       and exists (
               select 1
                 from public.testers t
                where t.email = lower(auth.jwt() ->> 'email')
           );
$$;

comment on function public.is_tester() is
    'True when the request is from a signed-in, non-anonymous user whose email is '
    'in public.testers. Every policy in the schema requires it.';


-- ==== function is_unlimited — 20260918000200_ten_a_day_and_a_door.sql

create or replace function public.is_unlimited()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
          from public.testers t
         where t.email = lower(auth.jwt() ->> 'email')
           and t.unlimited
    );
$$;

comment on function public.is_unlimited() is
    'True when the caller is a tester whose row lifts the daily ceiling. '
    'Answers about the caller alone.';


-- ==== function keep_the_daily_goal_under_its_ceiling — 20260930000200_four_columns_of_a_profile.sql

create or replace function public.keep_the_daily_goal_under_its_ceiling()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
    v_max integer;
begin
    -- Only the app: a signed-in request, as PostgREST makes one, writing its
    -- own profile. A migration, a fixture, a definer function or the owner with
    -- the service role is none of those and is not what this is guarding.
    if current_user <> 'authenticated'
       or (select auth.uid()) is distinct from new.id then
        return new;
    end if;
    -- And only when the goal is what is being written. A row is not re-judged
    -- every time something else on it moves: a goal of forty set while the
    -- account had a ceiling of sixty would otherwise make every later write to
    -- that profile fail the day the ceiling came off, which is a strange way
    -- for an exam date to stop saving.
    if tg_op = 'UPDATE' and new.daily_goal is not distinct from old.daily_goal then
        return new;
    end if;
    -- The size of a day is the owner's to give, one account at a time. Without
    -- a number on this account's tester row it is not the learner's to change
    -- at all, not even below the fifteen: ten is the product, not a setting.
    v_max := (select public.my_goal_max());
    if v_max is null then
        raise exception 'the size of the day is not this account''s to choose'
            using errcode = 'insufficient_privilege';
    end if;
    if new.daily_goal > v_max then
        raise exception 'a daily goal of % is above this account''s ceiling of %',
            new.daily_goal, v_max;
    end if;
    return new;
end;
$$;

comment on function public.keep_the_daily_goal_under_its_ceiling is
    'The size of the day, enforced where the client cannot get past it. A client '
    'may change profiles.daily_goal only on the account whose tester row carries '
    'max_daily_goal, and only up to it; everybody else''s goal is not theirs to '
    'change. Judges a goal being written, never an existing row.';


-- ==== function level_evidence — 20260927000100_a_new_question_not_the_same_one.sql

create or replace function public.level_evidence(p_section text)
returns table (
    level        text,
    since        timestamptz,
    level_window integer,
    answered     integer,
    correct      integer
)
language sql
stable
set search_path = ''
as $$
    with me as (
        select (select auth.uid()) as id
    ),
    cur as (
        select coalesce(sl.level, 'J2')              as level,
               coalesce(sl.changed_at, '-infinity')  as since
          from (select 1) one
          left join public.section_levels sl
                 on sl.user_id = (select id from me) and sl.section = p_section
    ),
    firsts as (
        select a.id, a.item_id, a.is_correct, a.answered_at, i.level,
               (a.replays > 0 or a.peeked) as helped
          from public.attempts a
          join public.items i on i.id = a.item_id
          join public.item_types it on it.id = i.item_type
         where a.user_id = (select id from me)
           and it.section = p_section
           and i.is_published
           and not exists (
                   select 1 from public.attempts b
                    where b.user_id = a.user_id
                      and b.item_id = a.item_id
                      and (b.answered_at, b.id) < (a.answered_at, a.id))
    ),
    shelf as (
        select count(*)::int as n
          from public.items i
          join public.item_types it on it.id = i.item_type
         cross join cur
         where it.section = p_section
           and i.level = cur.level
           and i.is_published
           and (not it.needs_picture
                or exists (select 1 from public.scenes sc
                            where sc.id = i.scene_id and sc.image_path is not null))
           and not exists (select 1 from firsts f
                            where f.item_id = i.id and f.answered_at < cur.since)
    ),
    win as (
        select least(case when (select count(*) from firsts) < 20 then 10 else 20 end,
                     (select n from shelf)) as w
    ),
    recent as (
        select f.is_correct
          from firsts f
         cross join cur
         where f.level = cur.level
           and f.answered_at >= cur.since
           and not f.helped
         order by f.answered_at desc, f.id desc
         limit (select w from win)
    )
    select cur.level,
           cur.since,
           (select w from win),
           (select count(*)::int from recent),
           (select count(*) filter (where recent.is_correct)::int from recent)
      from cur
     -- The same door as everything else: a non-tester is answered with nothing.
     where (select public.is_tester());
$$;

comment on function public.level_evidence is
    'The evidence a section''s level is judged on, for the caller: the level, since '
    'when, the window (ten, or twenty with a record, never more than the questions '
    'the level has left, and unjudgeable below five), and how many of the latest '
    'unaided first attempts at that level are in it and right.';


-- ==== function may_i_veto — 20260922000100_veto_a_question.sql

create or replace function public.may_i_veto()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select (select public.is_tester())
       and exists (
               select 1
                 from public.testers t
                where t.email = lower(auth.jwt() ->> 'email')
                  and t.may_veto
           );
$$;

comment on function public.may_i_veto() is
    'True when the caller is a tester whose row carries may_veto. The app draws '
    'the veto button on this; veto_item() re-checks it rather than trusting it.';


-- ==== function my_daily_max — 20260922000200_a_day_the_owner_sizes.sql

create or replace function public.my_daily_max()
returns integer
language sql
stable
set search_path = ''
as $$
    select coalesce((select public.my_goal_max()), public.daily_max());
$$;

comment on function public.my_daily_max is
    'The most this caller may answer in one Japanese calendar day, and the '
    'largest set they may ask for. daily_max() for everybody; the owner''s own '
    'number for the one row that carries one.';


-- ==== function my_goal_max — 20260922000200_a_day_the_owner_sizes.sql

create or replace function public.my_goal_max()
returns integer
language sql
stable
security definer
set search_path = ''
as $$
    select t.max_daily_goal::integer
      from public.testers t
     where t.email = lower(auth.jwt() ->> 'email');
$$;

comment on function public.my_goal_max is
    'The largest daily set this account may choose, when that is this account''s '
    'to choose, and null when it is not. The app draws the set-size picker on '
    'this; the trigger on profiles re-checks it rather than trusting it.';


-- ==== function my_streak — 20260913000300_stats_and_selection.sql

create or replace function public.my_streak()
returns integer
language sql
stable
as $$
    with days as (
        select distinct (answered_at at time zone 'Asia/Tokyo')::date as day
        from public.attempts
        where user_id = (select auth.uid())
    ),
    today as (
        select (now() at time zone 'Asia/Tokyo')::date as d
    ),
    -- A run of consecutive days shares (day - row_number()); take the run that
    -- contains today, or yesterday if today is not answered yet.
    runs as (
        select day, day - (row_number() over (order by day))::int as grp from days
    )
    select coalesce(
        (select count(*)::int
           from runs
          where grp = (select grp from runs
                        where day in ((select d from today), (select d - 1 from today))
                        order by day desc limit 1)),
        0);
$$;


-- ==== function next_items — 20260930000700_the_retest_walk_stops_early.sql

create or replace function public.next_items(p_limit integer default 5)
returns table (
    id                text,
    item_type         text,
    level             text,
    topic             text,
    stem              text,
    scene_id          text,
    scene_image_path  text,
    speaker_role      text,
    listener_role     text,
    channel           text,
    seed_cell_id      text,
    correct_index     smallint,
    explanation_ja    text,
    explanation_en    text,
    vocab_notes       jsonb,
    documents         jsonb,
    dialogue          jsonb,
    narration_clip_id text,
    narration_path    text,
    options           jsonb,
    times_seen        integer,
    stands_for        text,
    lesson_trap       text
)
language sql
stable
security invoker
set search_path = ''
set jit = off
as $$
    with recursive uid as (
        select (select auth.uid()) as id
    ),
    ladder as (
        select s.section,
               coalesce(sl.level, 'J2') as level,
               case coalesce(sl.level, 'J2') when 'J3' then 'J2' when 'J2' then 'J1' end as up,
               case coalesce(sl.level, 'J2') when 'J1' then 'J2' when 'J2' then 'J3' end as down
        from (values ('choukai'), ('choudokkai'), ('dokkai')) as s(section)
        left join public.section_levels sl
               on sl.user_id = (select id from uid) and sl.section = s.section
    ),
    seen as (
        select a.item_id,
               count(*)::int              as times_seen,
               bool_or(a.is_correct)      as ever_correct,
               max(a.answered_at)         as last_at
        from public.attempts a
        where a.user_id = (select id from uid)
        group by a.item_id
    ),
    -- The door: the smaller of what was asked for and what the day has left,
    -- unless this tester's ceiling is lifted. Today is counted as a range on
    -- answered_at from midnight in Japan, the form attempts_user_time_idx can
    -- answer, and the same form grade_attempt() counts with.
    bounds as (
        select case
            when (select public.is_unlimited()) then greatest(p_limit, 0)
            else least(
                greatest(p_limit, 0),
                greatest(
                    (select public.my_daily_max())
                    - (select count(*)::int
                         from public.attempts a
                        where a.user_id = (select id from uid)
                          and a.answered_at >= ((now() at time zone 'Asia/Tokyo')::date::timestamp
                                                at time zone 'Asia/Tokyo')),
                    0))
        end as n
    ),
    -- The last two weeks before the exam date, counted in Japan (G).
    exam as (
        select coalesce((
            select p.exam_date between (now() at time zone 'Asia/Tokyo')::date
                                   and (now() at time zone 'Asia/Tokyo')::date + 14
              from public.profiles p
             where p.id = (select id from uid)), false) as near
    ),
    weighted as (
        select a.item_id,
               a.is_correct,
               a.chosen_role,
               power(0.5, extract(epoch from now() - a.answered_at) / (30 * 86400)) as w
        from public.attempts a
        where a.user_id = (select id from uid)
    ),
    tag_accuracy as (
        select i.function as function,
               (coalesce(sum(w.w) filter (where w.is_correct), 0) + 1) / (sum(w.w) + 2) as accuracy
        from weighted w
        join public.items i on i.id = w.item_id
        where i.function is not null
        group by i.function
    ),
    -- H: 0.35, so the most accurate learner is pitched at the stated floor.
    type_pitch as (
        select t.id as item_type,
               coalesce(ty.accuracy, 0.5) as accuracy,
               least(greatest(0.85 - coalesce(ty.accuracy, 0.5) * 0.35, 0.50), 0.80) as target_p
        from public.item_types t
        left join (
            select i.item_type,
                   (coalesce(sum(w.w) filter (where w.is_correct), 0) + 1) / (sum(w.w) + 2) as accuracy
            from weighted w
            join public.items i on i.id = w.item_id
            group by i.item_type
        ) ty on ty.item_type = t.id
    ),
    sec_accuracy as (
        select it.section,
               (coalesce(sum(w.w) filter (where w.is_correct), 0) + 1) / (sum(w.w) + 2) as accuracy
        from weighted w
        join public.items i on i.id = w.item_id
        join public.item_types it on it.id = i.item_type
        group by it.section
    ),
    traps as (
        select w.chosen_role as role, sum(w.w) as times
        from weighted w
        where not w.is_correct
          and w.chosen_role <> ''
        group by w.chosen_role
    ),
    role_rarity as (
        select o.role,
               ln((select count(*) from public.items b where b.is_published)::numeric
                  / count(distinct o.item_id)) as rarity
        from public.item_options o
        join public.items i on i.id = o.item_id
        where i.is_published
          and o.position <> i.correct_index
        group by o.role
    ),
    trap_fit as (
        select o.item_id, sum(t.times * rr.rarity)::numeric as weight
        from public.item_options o
        join public.items i on i.id = o.item_id
        join traps t on t.role = o.role
        join role_rarity rr on rr.role = o.role
        where i.is_published
          and o.position <> i.correct_index
        group by o.item_id
    ),
    lessons as (
        select r.item_id, r.trap, r.missed, r.due_at, r.due_at <= now() as is_due
        from public.review_schedule r
        where r.user_id = (select id from uid)
    ),
    -- Every servable published question, at every level (B). `in_window` is
    -- the old pool: this section's level and the two beside it.
    pool as (
        select i.id, i.level, i.item_type, i.setting, i.function, it.section,
               la.level as at_level,
               la.up    as above,
               la.down  as below,
               coalesce(i.level = la.level or i.level = la.up or i.level = la.down, false)
                                                  as in_window,
               coalesce(sa.accuracy, 0.5)         as section_accuracy,
               s.item_id is not null              as is_seen,
               coalesce(s.ever_correct, false)    as ever_correct,
               s.last_at,
               coalesce(l.is_due, false)          as lesson_due,
               coalesce(l.missed, false)          as lesson_missed,
               -- Lower is more urgent. Same four terms, same weights.
               coalesce(ta.accuracy, 0.5)
                   + (coalesce(sa.accuracy, 0.5) - 0.5) * 0.20
                   - least(coalesce(tf.weight, 0), 5) * 0.06
                   + coalesce(abs(coalesce(d.p_correct, i.model_p_correct) - tp.target_p), 0.10) * 0.50
                   as weakness
        from public.items i
        join public.item_types it on it.id = i.item_type
        join ladder la on la.section = it.section
        join type_pitch tp on tp.item_type = i.item_type
        left join sec_accuracy sa on sa.section = it.section
        left join seen s on s.item_id = i.id
        left join tag_accuracy ta on ta.function = i.function
        left join trap_fit tf on tf.item_id = i.id
        left join public.v_item_difficulty d on d.item_id = i.id
        left join lessons l on l.item_id = i.id
        where i.is_published
          and (not it.needs_picture
               or exists (select 1 from public.scenes sc
                           where sc.id = i.scene_id and sc.image_path is not null))
    ),
    -- A: the lessons that are due, misses first, then the most overdue. Only
    -- the first two hundred: the walk below never goes further, so nothing
    -- here is built for a lesson it could not reach.
    due_lessons as (
        select d.*
        from (
            select l.item_id, l.trap, i.item_type, i.function,
                   row_number() over (order by l.missed desc, l.due_at, l.item_id) as priority
            from lessons l
            join public.items i on i.id = l.item_id
            where l.is_due
              and i.is_published
        ) d
        where d.priority <= 200
    ),
    -- A backlog is served two fifths of a set at a time.
    due_cap as (
        select greatest(1, ((select b.n from bounds b) * 2) / 5) as n
    ),
    -- Every role a published question offers as a wrong answer, once per
    -- question: what a lesson's trap is looked up in, as one join rather than
    -- a search per (lesson, question) pair.
    wrong_roles as (
        select distinct o.item_id, o.role
        from public.item_options o
        join public.items c on c.id = o.item_id
        where c.is_published
          and o.position <> c.correct_index
    ),
    -- ...and for each lesson, the unseen questions that re-test it, best
    -- first. The same rule grade_attempt() checks a `stands_for` against: the
    -- trap as a wrong answer, or for a lesson that never caught anybody, its
    -- 機能. Only a lesson's best `due_cap` are kept. The walk below stops once
    -- it has handed out `due_cap` questions, so when any lesson's turn comes,
    -- fewer than `due_cap` are taken, and its best free question is always
    -- among its first `due_cap`. Materialised, because the walk reads it once
    -- per lesson.
    sibling_options as materialized (
        select r.lesson_id, r.sibling_id, r.pick
        from (
            select c.lesson_id, c.sibling_id,
                   row_number() over (partition by c.lesson_id
                                      order by (c.level = c.at_level) desc, c.in_window desc,
                                               c.weakness, c.sibling_id) as pick
            from (
                select dl.item_id as lesson_id, p.id as sibling_id,
                       p.level, p.at_level, p.in_window, p.weakness
                from due_lessons dl
                join pool p on p.item_type = dl.item_type and not p.is_seen
                join wrong_roles wr on wr.item_id = p.id and wr.role = dl.trap
                where dl.trap is not null
                union all
                select dl.item_id, p.id, p.level, p.at_level, p.in_window, p.weakness
                from due_lessons dl
                join pool p on p.item_type = dl.item_type and not p.is_seen
                where dl.trap is null
                  and (dl.function is null or p.function = dl.function)
            ) c
        ) r
        where r.pick <= (select dc.n from due_cap dc)
    ),
    -- One question per lesson, handed out in lesson order: each lesson takes
    -- its best question that no earlier lesson has taken. Two misses on the
    -- same trap — the commonest case there is — are two different questions,
    -- not one question and a lesson left waiting. A lesson whose questions are
    -- all taken, or which has none, is skipped and waits for a later set. The
    -- walk stops as soon as the set's share of the backlog is handed out.
    siblings (priority, lesson_id, trap, sibling_id, taken, served) as (
        select 0::bigint, null::text, null::text, null::text, array[]::text[], 0
        union all
        select dl.priority, dl.item_id, dl.trap, nxt.sibling_id,
               case when nxt.sibling_id is null then sb.taken
                    else sb.taken || nxt.sibling_id end,
               sb.served + case when nxt.sibling_id is null then 0 else 1 end
        from siblings sb
        join due_lessons dl on dl.priority = sb.priority + 1
        left join lateral (
            select so.sibling_id
              from sibling_options so
             where so.lesson_id = dl.item_id
               and not (so.sibling_id = any (sb.taken))
             order by so.pick
             limit 1
        ) nxt on true
        where sb.served < (select dc.n from due_cap dc)
    ),
    due as (
        select sb.sibling_id as id, 0 as bucket, sb.priority::double precision as rank,
               sb.lesson_id as stands_for, sb.trap as lesson_trap
        from siblings sb
        where sb.sibling_id is not null
        order by sb.priority
        limit (select dc.n from due_cap dc)
    ),
    stretch as (
        select p.id, 2 as bucket, random() as rank,
               null::text as stands_for, null::text as lesson_trap
        from pool p
        where (select b.n from bounds b) >= 5
          and p.level = p.above
          and not p.is_seen
        order by p.section_accuracy desc, random()
        limit 1
    ),
    fresh_size as (
        select greatest(
            (select b.n from bounds b)
            - (select count(*) from due)
            - (select count(*) from stretch), 1) as n
    ),
    sec_quota as (
        select it.section,
               round(
                   sum(it.exam_questions)::numeric
                   / (select sum(t.exam_questions) from public.item_types t)
                   * (select f.n from fresh_size f)
               ) as quota
        from public.item_types it
        group by it.section
    ),
    fresh_ranked as (
        select p.id,
               p.weakness
                   + greatest(0, row_number() over (partition by p.section
                                             order by p.weakness, p.id)
                                 - coalesce(q.quota, 99))
                     * case when (select e.near from exam e) then 1.0 else 0.25 end
                   + (row_number() over (partition by p.item_type
                                             order by p.weakness, p.id) - 1) * 0.15
                   + (row_number() over (partition by coalesce(p.setting, p.id)
                                             order by p.weakness, p.id) - 1) * 0.05
                   + random() / 50 as rank
        from pool p
        left join sec_quota q on q.section = p.section
        where p.level = p.at_level
          and not p.is_seen
    ),
    fresh as (
        select f.id, 1 as bucket, f.rank,
               null::text as stands_for, null::text as lesson_trap
        from fresh_ranked f
        order by f.rank
        limit (select f.n from fresh_size f)
    ),
    rest as (
        select p.id,
               case when not p.is_seen and p.in_window                then 3
                    when not p.is_seen                                then 4
                    when p.last_at <= now() - interval '20 hours'     then 5
                    else                                                   6
               end as bucket,
               (case when not p.is_seen then
                        -- Own level, then above, then below, then further;
                        -- inside a band, weakest ground first. The weakness is
                        -- squeezed under one so a band never mixes with the next.
                        case when p.level = p.at_level then 0
                             when p.level = p.above    then 1
                             when p.level = p.below    then 2
                             else                           3
                        end
                        + least(greatest(p.weakness, 0), 1.8) / 2
                        + random() / 1e6
                    else
                        -- A lesson due with no new question left to re-test it,
                        -- misses first; then questions never answered right; the
                        -- level above before the one below; then longest ago. The
                        -- noise is a fraction of a second of `last_at` (I).
                        case when p.lesson_due and p.lesson_missed then 0
                             when p.lesson_due                     then 1
                             when not p.ever_correct               then 2
                             else                                       3
                        end
                        + case when p.level = p.below then 0.5 else 0 end
                        + coalesce(extract(epoch from p.last_at), 0) / 1e12
                        + random() / 1e15
               end)::double precision as rank,
               null::text as stands_for, null::text as lesson_trap
        from pool p
        -- A question already met comes back only from inside the window.
        where not p.is_seen or p.in_window
    ),
    chosen as (
        select distinct on (u.id) u.id, u.bucket, u.rank, u.stands_for, u.lesson_trap
        from (
            select * from due
            union all select * from fresh
            union all select * from stretch
            union all select * from rest
        ) u
        order by u.id, u.bucket, u.rank
    )
    select
        i.id, i.item_type, i.level, i.topic, i.stem, i.scene_id,
        (select s.image_path from public.scenes s where s.id = i.scene_id) as scene_image_path,
        i.speaker_role, i.listener_role, i.channel, i.seed_cell_id,
        i.correct_index, i.explanation_ja, i.explanation_en, i.vocab_notes,
        i.documents,
        (
            select coalesce(
                jsonb_agg(
                    turn || jsonb_build_object(
                        'audio_path',
                        (select c.audio_path from public.audio_clips c
                          where c.id = turn ->> 'clip_id')
                    )
                    order by idx
                ),
                '[]'::jsonb
            )
            from jsonb_array_elements(i.dialogue) with ordinality as t(turn, idx)
        ) as dialogue,
        i.narration_clip_id,
        (select c.audio_path from public.audio_clips c where c.id = i.narration_clip_id) as narration_path,
        (
            select jsonb_agg(
                       jsonb_build_object(
                           'position',   o.position,
                           'text',       o.text,
                           'role',       o.role,
                           'why',        o.why,
                           'clip_id',    o.clip_id,
                           'audio_path', c.audio_path
                       )
                       order by o.position
                   )
            from public.item_options o
            left join public.audio_clips c on c.id = o.clip_id
            where o.item_id = i.id
        ) as options,
        coalesce(s.times_seen, 0) as times_seen,
        ch.stands_for,
        ch.lesson_trap
    from chosen ch
    join public.items i on i.id = ch.id
    left join seen s on s.item_id = i.id
    order by ch.bucket, ch.rank
    limit (select b.n from bounds b);
$$;

comment on function public.next_items is
    'The practice queue. Due lessons first, each re-tested by an unseen question '
    'that sets the same trap (stands_for names the lesson); then fresh questions '
    'ranked by weakness, the difficulty pitch and the traps that caught this '
    'learner, leaned toward the exam''s own section mix (strictly, in the last two '
    'weeks before the exam date); one stretch item; then every other unseen '
    'question, at any level, before any question already met. Takes a size and '
    'reads everything else from the record. The size it serves is capped by what '
    'the day has left.';


-- ==== function pace_max_scale — 20260927000100_a_new_question_not_the_same_one.sql

create or replace function public.pace_max_scale()
returns numeric
language sql
immutable
set search_path = ''
as $$ select 1.6::numeric; $$;

comment on function public.pace_max_scale is
    'The reading clock''s largest scale on seconds_per_item (pace.ts MAX_SCALE). '
    'schedule_review() holds a right answer slower than this.';


-- ==== function questions_left — 20260927000100_a_new_question_not_the_same_one.sql

create or replace function public.questions_left(p_user uuid, p_section text, p_level text)
returns integer
language sql
stable
set search_path = ''
as $$
    select count(*)::int
      from public.items i
      join public.item_types it on it.id = i.item_type
     where it.section = p_section
       and i.level = p_level
       and i.is_published
       and (not it.needs_picture
            or exists (select 1 from public.scenes sc
                        where sc.id = i.scene_id and sc.image_path is not null))
       and not exists (select 1 from public.attempts a
                        where a.user_id = p_user and a.item_id = i.id);
$$;


-- ==== function refresh_item_stats — 20260927000100_a_new_question_not_the_same_one.sql

create or replace function public.refresh_item_stats()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_rows integer;
begin
    -- From nothing, every time: a history that was reset must not leave its
    -- counts behind, and a full recount is still one pass at this scale. The
    -- `where true` is for pg-safeupdate, which refuses a bare delete.
    delete from public.item_stats where true;

    -- Each person's first answer to each question, and never a timeout. A
    -- second answer comes after the explanation was read, and a timeout is a
    -- fact about the clock (or a phone put down), not about the Japanese.
    insert into public.item_stats (item_id, answered, correct, p_correct, updated_at)
    select f.item_id,
           count(*)::int,
           count(*) filter (where f.is_correct)::int,
           count(*) filter (where f.is_correct)::numeric / count(*),
           now()
      from (
        select distinct on (a.user_id, a.item_id)
               a.item_id, a.is_correct, a.chosen_role
          from public.attempts a
         order by a.user_id, a.item_id, a.answered_at, a.id
      ) f
     where f.chosen_role <> 'timed_out'
     group by f.item_id;
    get diagnostics v_rows = row_count;
    return v_rows;
end;
$$;

comment on function public.refresh_item_stats is
    'Recount the shared bank''s per-item success rates from each person''s first '
    'answer, timeouts left out, from nothing. Run by the nightly job as the service '
    'role; never on the practice path.';


-- ==== function refuse_unlisted_signup — 20260921000100_no_new_accounts.sql

create or replace function public.refuse_unlisted_signup()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    -- Anything but the auth service is the owner, deliberately.
    if session_user is distinct from 'supabase_auth_admin'
       and coalesce(current_setting('role', true), 'none') is distinct from 'supabase_auth_admin'
    then
        return new;
    end if;

    if new.email is null
       or not exists (select 1
                        from public.testers t
                       where t.email = lower(new.email))
    then
        raise exception 'this app is not open for sign-up'
            using errcode = 'check_violation',
                  hint = 'The app is in private testing and is not accepting new accounts.';
    end if;

    return new;
end;
$$;

comment on function public.refuse_unlisted_signup() is
    'Refuses a sign-up for an address the owner has not already listed in '
    'public.testers. Applies to the auth service''s connection, which is the '
    'path open to the internet.';


-- ==== function reset_my_progress — 20260920000100_start_again.sql

create or replace function public.reset_my_progress()
returns jsonb
language plpgsql
security definer
-- Pinned, like the other two functions the app can call: the body reads
-- `is_tester()` and five tables, and an unpinned path lets a caller who can
-- create a temporary schema decide what those names mean.
set search_path = ''
as $$
declare
    v_user     uuid := (select auth.uid());
    v_attempts integer;
    v_sessions integer;
    v_reviews  integer;
    v_notes    integer;
    v_levels   integer;
begin
    -- The same door as every policy in the schema. A definer function is not
    -- covered by row-level security, so it has to ask on its own account.
    if v_user is null or not (select public.is_tester()) then
        raise exception 'reset_my_progress is for a signed-in tester';
    end if;

    delete from public.attempts where user_id = v_user;
    get diagnostics v_attempts = row_count;

    delete from public.review_schedule where user_id = v_user;
    get diagnostics v_reviews = row_count;

    delete from public.review_notes where user_id = v_user;
    get diagnostics v_notes = row_count;

    delete from public.practice_sessions where user_id = v_user;
    get diagnostics v_sessions = row_count;

    -- Deleted rather than set back to 'J2': a section with no row is exactly
    -- what a learner who has never answered anything has, and every reader of
    -- this table (v_my_levels, next_items) already coalesces a missing row to
    -- the starting level. Writing the default back would leave `changed_at`
    -- and `moves` saying the level had been considered and kept.
    delete from public.section_levels where user_id = v_user;
    get diagnostics v_levels = row_count;

    -- The one-line summary of the three, and nothing else on the profile.
    -- `default` rather than a literal, so the starting level lives in the
    -- column definition and not in a second place that can drift from it.
    update public.profiles
       set target_level     = default,
           level_changed_at = now(),
           updated_at       = now()
     where id = v_user;

    return jsonb_build_object(
        'attempts', v_attempts,
        'sessions', v_sessions,
        'reviews',  v_reviews,
        'notes',    v_notes,
        'levels',   v_levels
    );
end;
$$;

comment on function public.reset_my_progress is
    'Erases the caller''s own practice history — answers, sessions, the spacing '
    'schedule, review notes and the three section levels — and puts the level '
    'summary back to the starting default. Takes no arguments and reads the '
    'user from the session, so it cannot be aimed at anybody else or at part of '
    'one history. Settings, entitlements and item reports are left alone.';


-- ==== function review_interval — 20260916000500_shared_bank_and_spacing.sql

create or replace function public.review_interval(p_step smallint)
returns interval
language sql
immutable
set search_path = ''
as $$
    select (array[
        interval '20 hours',   -- 0: a miss. Tonight's sleep, then again.
        interval '3 days',     -- 1
        interval '7 days',     -- 2
        interval '21 days',    -- 3
        interval '60 days'     -- 4: known. Checked twice a term.
    ])[least(greatest(p_step, 0), 4) + 1];
$$;


-- ==== function revoke_entitlement — 20260915000400_entitlement_grants.sql

create or replace function public.revoke_entitlement(
    p_user_id uuid,
    p_product text default 'ads_free',
    p_note    text default null
)
returns public.entitlements
language plpgsql
security definer
set search_path = ''
as $$
declare
    row public.entitlements;
begin
    update public.entitlements
       set revoked_at = now(),
           note       = coalesce(p_note, note)
     where user_id = p_user_id
       and product = p_product
    returning * into row;

    return row;
end;
$$;

comment on function public.revoke_entitlement is
    'Withdraw an entitlement without deleting the record of it having existed.';


-- ==== function schedule_review — 20260927000100_a_new_question_not_the_same_one.sql

create or replace function public.schedule_review()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_lesson  text := coalesce(new.stands_for, new.item_id);
    v_step    smallint;
    v_trap    text;
    v_known   boolean;
    v_secs    smallint;
    v_slow    boolean;
    v_helped  boolean;
    v_due     timestamptz;
    v_exam    timestamptz;
begin
    select r.step, r.trap
      into v_step, v_trap
      from public.review_schedule r
     where r.user_id = new.user_id and r.item_id = v_lesson;
    v_known := found;

    select it.seconds_per_item
      into v_secs
      from public.items i
      join public.item_types it on it.id = i.item_type
     where i.id = new.item_id;

    -- A self-paced type is slow past the most its clock ever gives; a type the
    -- audio paces is slow thirty seconds after the audio ended (the exam moves
    -- on a few seconds after each question). With no think time, the old rule:
    -- two minutes for the whole item.
    v_slow := case
        when v_secs is not null then
            coalesce(new.think_ms, new.elapsed_ms, 0) > v_secs * 1000 * public.pace_max_scale()
        when new.think_ms is not null then
            new.think_ms > 30000
        else
            coalesce(new.elapsed_ms, 0) > 120000
    end;
    v_helped := new.replays > 0 or new.peeked;

    if not new.is_correct then
        v_step := 0;
        if new.chosen_role <> 'timed_out' then
            v_trap := new.chosen_role;
        end if;
    elsif v_slow or v_helped then
        v_step := coalesce(v_step, 0);
    elsif not v_known then
        v_step := 1;
    else
        v_step := least(v_step + 1, 4);
    end if;

    v_due := new.answered_at + public.review_interval(v_step);

    select (p.exam_date::timestamp at time zone 'Asia/Tokyo')
      into v_exam
      from public.profiles p
     where p.id = new.user_id;
    if v_exam is not null and v_exam > new.answered_at
       and v_due > v_exam - interval '2 days' then
        v_due := greatest(new.answered_at + interval '20 hours', v_exam - interval '2 days');
    end if;

    insert into public.review_schedule (user_id, item_id, due_at, step, last_at, trap, missed)
    values (new.user_id, v_lesson, v_due, v_step, new.answered_at, v_trap, not new.is_correct)
    on conflict (user_id, item_id) do update
       set due_at  = excluded.due_at,
           step    = excluded.step,
           last_at = excluded.last_at,
           trap    = excluded.trap,
           missed  = excluded.missed;
    return new;
end;
$$;

comment on function public.schedule_review is
    'Keep review_schedule in step with attempts. A 類題 moves the lesson it stands '
    'for. Wrong drops to the bottom and remembers the trap; right but slow, or '
    'with a replay, holds; right at first sight starts on the three-day rung; '
    'otherwise right climbs one. A due date is brought forward to land before the '
    'exam.';


-- ==== function stamp_item_feedback — 20260919000400_report_a_bad_question.sql

create or replace function public.stamp_item_feedback()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    new.user_id := (select auth.uid());
    if new.user_id is null then
        raise exception 'feedback requires an authenticated session';
    end if;
    new.updated_at := now();
    if tg_op = 'UPDATE' then
        new.created_at := old.created_at;
    end if;
    return new;
end;
$$;


-- ==== function sync_profile_identity — 20260913000200_users.sql

create or replace function public.sync_profile_identity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    if coalesce(old.is_anonymous, false) is distinct from coalesce(new.is_anonymous, false) then
        update public.profiles
           set is_anonymous = coalesce(new.is_anonymous, false),
               linked_at    = case
                                  when coalesce(new.is_anonymous, false) then linked_at
                                  else coalesce(linked_at, now())
                              end,
               updated_at   = now()
         where id = new.id;
    end if;
    return new;
end;
$$;


-- ==== function veto_item — 20260922000100_veto_a_question.sql

create or replace function public.veto_item(p_item_id text, p_note text default '')
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user uuid := (select auth.uid());
begin
    if v_user is null then
        raise exception 'a veto needs an authenticated session';
    end if;
    if not (select public.may_i_veto()) then
        raise exception 'this account may not veto a question';
    end if;
    if not exists (select 1 from public.items where id = p_item_id) then
        raise exception 'no such item: %', p_item_id;
    end if;

    update public.items
       set is_published = false
     where id = p_item_id;

    insert into public.item_vetoes (item_id, user_id, note)
    values (p_item_id, v_user, coalesce(left(p_note, 500), ''))
    on conflict (item_id) do nothing;
end;
$$;

comment on function public.veto_item(text, text) is
    'Unpublish one question and record who did it. Requires may_i_veto(). The '
    'item stays in the table so that attempts, schedules and reports pointing '
    'at it keep resolving; next_items() drops it because it filters on '
    'is_published.';


-- ==== trigger adjust_level_after_insert — 20260916000100_auto_level_and_exam_date.sql

create trigger adjust_level_after_insert
    after insert on public.attempts
    for each row execute function public.adjust_level();


-- ==== trigger grade_attempt_before_insert — 20260913000200_users.sql

create trigger grade_attempt_before_insert
    before insert on public.attempts
    for each row execute function public.grade_attempt();


-- ==== trigger on_auth_user_created — 20260913000200_users.sql

create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user();


-- ==== trigger on_auth_user_identity_changed — 20260913000200_users.sql

create trigger on_auth_user_identity_changed
    after update on auth.users
    for each row execute function public.sync_profile_identity();


-- ==== trigger on_auth_user_signup — 20260921000100_no_new_accounts.sql

create trigger on_auth_user_signup
    before insert on auth.users
    for each row execute function public.refuse_unlisted_signup();


-- ==== trigger profiles_daily_goal_ceiling — 20260922000200_a_day_the_owner_sizes.sql

create trigger profiles_daily_goal_ceiling
    before insert or update on public.profiles
    for each row execute function public.keep_the_daily_goal_under_its_ceiling();


-- ==== trigger schedule_review_after_insert — 20260916000500_shared_bank_and_spacing.sql

create trigger schedule_review_after_insert
    after insert on public.attempts
    for each row execute function public.schedule_review();


-- ==== trigger stamp_item_feedback_before_write — 20260919000400_report_a_bad_question.sql

create trigger stamp_item_feedback_before_write
    before insert or update on public.item_feedback
    for each row execute function public.stamp_item_feedback();
