#!/usr/bin/env python3
"""Check the app's queries against the real schema.

TypeScript will happily compile `select("is_corect")`. The type checker only
knows the shape we *claimed* the database has; it cannot know whether that claim
is true. The mismatch shows up at runtime, on a device, as an empty screen.

So this reads every Supabase call in the client and emits SQL that asserts each
table, view, column and function it names actually exists. `run.sh` pipes that
into the same throwaway database the schema tests use, which makes "the app and
the schema agree" a thing that fails in CI rather than in someone's hand.

It is a deliberately shallow parser — it matches call chains, not TypeScript —
and that is fine: it only needs to find the identifiers, and anything it cannot
parse it simply does not assert.

    supabase/test/contract.py client/src/lib > /tmp/contract.sql
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# supabase.from("table") ... up to the end of the statement, OR up to the next
# query, whichever comes first. Anchored on the client itself so that
# supabase.storage.from("audio") — a bucket, not a table — is not mistaken for
# one.
#
# The "next query" half matters because a screen that needs two tables at once
# fetches them in one Promise.all, which is one statement with two chains in it.
# Stopping only at the semicolon attributed the second query's filters to the
# first query's table, and reported a perfectly good column as missing from a
# table that never mentioned it.
CHAIN = re.compile(
    r'\bsupabase\s*\.\s*from\(\s*"([a-z_0-9]+)"\s*\)'
    r'(.*?)(?=;|\bsupabase\s*\.\s*(?:from|rpc)\()',
    re.S,
)
SELECT = re.compile(r'\.select\(\s*"([^"]*)"')
OBJECT_KEYS = re.compile(r'\.(?:insert|update|upsert)\(\s*\{(.*?)\}', re.S)
KEY = re.compile(r'(?:^|[\s,{])([a-z_][a-z_0-9]*)\s*:', re.M)
COLUMN_FILTER = re.compile(r'\.(?:eq|neq|gt|gte|lt|lte|like|ilike|is|in|not|order)\(\s*"([a-z_0-9]+)"')
RPC = re.compile(r'\.rpc\(\s*"([a-z_0-9]+)"\s*(?:,\s*\{(.*?)\})?\s*\)', re.S)

# Written by triggers, never sent by the client — naming one here would be a bug
# worth catching, so they are not silently allowed anywhere else.
SKIP_KEYS = {"true", "false", "null"}


def columns_for_chain(body: str) -> set[str]:
    cols: set[str] = set()
    for raw in SELECT.findall(body):
        for piece in raw.split(","):
            name = piece.strip().split("(")[0].strip()
            if name and name != "*":
                cols.add(name)
    for obj in OBJECT_KEYS.findall(body):
        cols.update(k for k in KEY.findall(obj) if k not in SKIP_KEYS)
    cols.update(COLUMN_FILTER.findall(body))
    return cols


def scan(paths: list[Path]) -> tuple[dict[str, set[str]], dict[str, set[str]]]:
    tables: dict[str, set[str]] = {}
    rpcs: dict[str, set[str]] = {}
    for path in paths:
        src = path.read_text(encoding="utf-8")
        for table, body in CHAIN.findall(src):
            tables.setdefault(table, set()).update(columns_for_chain(body))
        for fn, args in RPC.findall(src):
            rpcs.setdefault(fn, set()).update(
                k for k in KEY.findall(args or "") if k not in SKIP_KEYS
            )
    return tables, rpcs


def emit(tables: dict[str, set[str]], rpcs: dict[str, set[str]]) -> str:
    out = [
        "-- Generated by supabase/test/contract.py — do not edit.",
        "-- Asserts that every table, view, column and function the app calls exists.",
        "\\set ON_ERROR_STOP on",
        "",
    ]
    for table in sorted(tables):
        out.append(
            f"do $$ begin perform test.check("
            f"to_regclass('public.{table}') is not null, "
            f"'app reads public.{table}'); end $$;"
        )
        for column in sorted(tables[table]):
            out.append(
                "do $$ begin perform test.check(exists ("
                "select 1 from information_schema.columns "
                f"where table_schema='public' and table_name='{table}' "
                f"and column_name='{column}'), "
                f"'  public.{table}.{column}'); end $$;"
            )
    for fn in sorted(rpcs):
        out.append(
            "do $$ begin perform test.check(exists ("
            f"select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace "
            f"where n.nspname='public' and p.proname='{fn}'), "
            f"'app calls public.{fn}()'); end $$;"
        )
        for arg in sorted(rpcs[fn]):
            out.append(
                "do $$ begin perform test.check(exists ("
                "select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace "
                f"where n.nspname='public' and p.proname='{fn}' "
                f"and '{arg}' = any(p.proargnames)), "
                f"'  {fn}({arg} => ...)'); end $$;"
            )
    out.append("\\echo 'CLIENT CONTRACT OK'")
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    roots = [Path(a) for a in argv[1:]] or [Path("client/src/lib")]
    files: list[Path] = []
    for root in roots:
        files.extend(sorted(root.rglob("*.ts")) if root.is_dir() else [root])
    tables, rpcs = scan(files)
    if not tables and not rpcs:
        print("-- no Supabase calls found; check the path", file=sys.stderr)
        return 1
    sys.stdout.write(emit(tables, rpcs))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
