"""The constants the app needs from the pipeline, written out as TypeScript.

Some facts live in Python and are needed in the app: every distractor role a
question can carry (`bjt/fidelity/roles.py`), and the Japanese name of every
seed-table tag (`seedtable/*.json`). Copied by hand, a role the app does not
know falls through to a generic "この場面に合わない", and a tag shows on the
progress screen as its id (`phone_absence`). So they are generated:

    python -m bjt.client_constants          # rewrite client/src/lib/generated.ts
    python -m bjt.client_constants --check  # exit 1 if it is out of date

and `tests/test_client_constants.py` fails when the committed file is not what
this module writes. The app types its role table as a `Record` over the
generated role list, so a role added here and not described there is a type
error rather than a generic sentence on a learner's screen.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys
from collections import Counter, defaultdict

from . import config
from .fidelity.roles import DISTRACTOR_ROLES

ROOT = pathlib.Path(__file__).resolve().parent.parent
TARGET = ROOT / "client" / "src" / "lib" / "generated.ts"

#: The seed-table axes a tag can come from, as v_my_tag_stats names them. The
#: fourth axis, channel, is four fixed words the app already translates.
TAG_AXES = {"function": "functions", "relation": "relations", "setting": "settings"}


def distractor_roles() -> list[str]:
    """Every distractor role any type uses, each once, in the order the enums
    first name them — so the file changes only when a role does."""
    seen: dict[str, None] = {}
    for roles in DISTRACTOR_ROLES.values():
        for role in roles:
            seen.setdefault(role, None)
    return list(seen)


def tag_labels(seedtable_dir: pathlib.Path | None = None) -> dict[str, dict[str, str]]:
    """The Japanese label of every tag on each axis, across every seed table.

    One id can be labelled in more than one table (`request` is 依頼する in
    three of them). The label most tables agree on wins, ties to the
    alphabetically first, so the output does not depend on file order."""
    directory = pathlib.Path(seedtable_dir or config.SEEDTABLE_DIR)
    seen: dict[str, dict[str, Counter]] = {axis: defaultdict(Counter) for axis in TAG_AXES}
    for path in sorted(directory.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        for axis, key in TAG_AXES.items():
            for entry in data.get(key, []):
                if entry.get("id") and entry.get("ja"):
                    seen[axis][entry["id"]][entry["ja"]] += 1
    return {
        axis: {
            tag: sorted(labels.items(), key=lambda kv: (-kv[1], kv[0]))[0][0]
            for tag, labels in sorted(by_tag.items())
        }
        for axis, by_tag in seen.items()
    }


def render(seedtable_dir: pathlib.Path | None = None) -> str:
    roles = distractor_roles()
    labels = tag_labels(seedtable_dir)
    lines = [
        "// Generated by `python -m bjt.client_constants` from bjt/fidelity/roles.py and",
        "// seedtable/*.json. Do not edit by hand: tests/test_client_constants.py fails",
        "// when this file is not what the generator writes.",
        "",
        "/** Every distractor role a question can carry, across all problem types. */",
        "export const DISTRACTOR_ROLES = [",
        *[f"  {json.dumps(r)}," for r in roles],
        "] as const;",
        "",
        "export type DistractorRole = (typeof DISTRACTOR_ROLES)[number];",
        "",
        "/** The Japanese name of every seed-table tag, by the axis v_my_tag_stats",
        " *  reports it on. Channel is not here: the app translates its four words. */",
        "export const TAG_LABELS: Record<\"function\" | \"relation\" | \"setting\", Record<string, string>> = {",
    ]
    for axis in TAG_AXES:
        lines.append(f"  {axis}: {{")
        for tag, label in labels[axis].items():
            lines.append(f"    {json.dumps(tag)}: {json.dumps(label, ensure_ascii=False)},")
        lines.append("  },")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the committed file is out of date, and write nothing")
    args = parser.parse_args(argv)
    text = render()
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
    if args.check:
        if current != text:
            print(f"{TARGET.relative_to(ROOT)} is out of date: run python -m bjt.client_constants",
                  file=sys.stderr)
            return 1
        return 0
    if current != text:
        TARGET.write_text(text, encoding="utf-8")
        print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
