/**
 * The constants the app needs from the pipeline, written out as TypeScript.
 *
 * Some facts live in the pipeline and are needed in the app: every distractor
 * role a question can carry (`bjt/fidelity/roles.ts`), and the Japanese name of
 * every seed-table tag (`seedtable/*.json`). Copied by hand, a role the app does
 * not know falls through to a generic "この場面に合わない", and a tag shows on the
 * progress screen as its id (`phone_absence`). So they are generated:
 *
 *     node bjt/client_constants.ts          # rewrite client/src/lib/generated.ts
 *     node bjt/client_constants.ts --check  # exit 1 if it is out of date
 *
 * and `tests/client_constants.test.ts` fails when the committed file is not what
 * this module writes. The app types its role table as a `Record` over the
 * generated role list, so a role added here and not described there is a type
 * error rather than a generic sentence on a learner's screen.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { ArgumentParser } from "./cli/argparse.ts";
import * as config from "./config.ts";
import { DISTRACTOR_ROLES } from "./fidelity/roles.ts";
import { dumps, loads } from "./pyjson.ts";
import { eprint, get, print, sorted, SystemExit, truthy } from "./py.ts";

export const ROOT = path.resolve(import.meta.dirname, "..");
export const TARGET = path.join(ROOT, "client", "src", "lib", "generated.ts");

/** The seed-table axes a tag can come from, as v_my_tag_stats names them. The
 *  fourth axis, channel, is four fixed words the app already translates. */
export const TAG_AXES: Record<string, string> = { function: "functions", relation: "relations", setting: "settings" };


/** Every distractor role any type uses, each once, in the order the enums
 *  first name them — so the file changes only when a role does. */
export function distractorRoles(): string[] {
  const seen = new Set<string>();
  for (const roles of Object.values(DISTRACTOR_ROLES)) {
    for (const role of roles) {
      seen.add(role);
    }
  }
  return [...seen];
}


/** The Japanese label of every tag on each axis, across every seed table.
 *
 *  One id can be labelled in more than one table (`request` is 依頼する in
 *  three of them). The label most tables agree on wins, ties to the
 *  alphabetically first, so the output does not depend on file order. */
export function tagLabels(opts: { seedtableDir?: string | null } = {}): Record<string, Record<string, string>> {
  const directory = opts.seedtableDir || config.SEEDTABLE_DIR;
  const seen: Record<string, Map<string, Map<string, number>>> = {};
  for (const axis of Object.keys(TAG_AXES)) seen[axis] = new Map();
  const files = sorted(readdirSync(directory).filter((name) => name.endsWith(".json")));
  for (const name of files) {
    const data = loads(readFileSync(path.join(directory, name), "utf8"));
    for (const [axis, key] of Object.entries(TAG_AXES)) {
      for (const entry of get(data, key, []) as Record<string, any>[]) {
        if (truthy(get(entry, "id")) && truthy(get(entry, "ja"))) {
          const byTag = seen[axis];
          if (!byTag.has(entry["id"])) byTag.set(entry["id"], new Map());
          const labels = byTag.get(entry["id"])!;
          labels.set(entry["ja"], (labels.get(entry["ja"]) ?? 0) + 1);
        }
      }
    }
  }
  const out: Record<string, Record<string, string>> = {};
  for (const [axis, byTag] of Object.entries(seen)) {
    out[axis] = {};
    for (const [tag, labels] of sorted(byTag.entries(), { key: (kv) => kv[0] })) {
      out[axis][tag] = sorted(labels.entries(), { key: (kv) => [-kv[1], kv[0]] })[0][0];
    }
  }
  return out;
}


export function render(opts: { seedtableDir?: string | null } = {}): string {
  const roles = distractorRoles();
  const labels = tagLabels({ seedtableDir: opts.seedtableDir ?? null });
  const lines = [
    "// Generated by `node bjt/client_constants.ts` from bjt/fidelity/roles.ts and",
    "// seedtable/*.json. Do not edit by hand: tests/client_constants.test.ts fails",
    "// when this file is not what the generator writes.",
    "",
    "/** Every distractor role a question can carry, across all problem types. */",
    "export const DISTRACTOR_ROLES = [",
    ...roles.map((r) => `  ${dumps(r)},`),
    "] as const;",
    "",
    "export type DistractorRole = (typeof DISTRACTOR_ROLES)[number];",
    "",
    "/** The Japanese name of every seed-table tag, by the axis v_my_tag_stats",
    " *  reports it on. Channel is not here: the app translates its four words. */",
    "export const TAG_LABELS: Record<\"function\" | \"relation\" | \"setting\", Record<string, string>> = {",
  ];
  for (const axis of Object.keys(TAG_AXES)) {
    lines.push(`  ${axis}: {`);
    for (const [tag, label] of Object.entries(labels[axis])) {
      lines.push(`    ${dumps(tag)}: ${dumps(label, { ensureAscii: false })},`);
    }
    lines.push("  },");
  }
  lines.push("};");
  return lines.join("\n") + "\n";
}


export function main(opts: { argv?: string[] | null } = {}): number {
  const parser = new ArgumentParser({
    prog: path.basename(process.argv[1] ?? ""),
    description: "The constants the app needs from the pipeline, written out as TypeScript.",
  });
  parser.addArgument("--check", {
    action: "store_true",
    help: "exit 1 if the committed file is out of date, and write nothing",
  });
  const args = parser.parseArgs(opts.argv ?? process.argv.slice(2));
  const text = render();
  const current = existsSync(TARGET) ? readFileSync(TARGET, "utf8") : "";
  if (args.check) {
    if (current !== text) {
      eprint(`${path.relative(ROOT, TARGET)} is out of date: run node bjt/client_constants.ts`);
      return 1;
    }
    return 0;
  }
  if (current !== text) {
    writeFileSync(TARGET, text, "utf8");
    print(`wrote ${path.relative(ROOT, TARGET)}`);
  }
  return 0;
}


if (import.meta.main) {
  try {
    process.exitCode = main();
  } catch (e) {
    if (!(e instanceof SystemExit)) throw e;
    process.exitCode = e.code;
  }
}
