-- goi_bunpou_J2_002: 1 × goi_bunpou (J2)
-- generated 2026-10-10T20:05:52+00:00 by claude-sonnet-5
-- Produced by bjt publish. Idempotent: re-running replaces these rows.

insert into bundles (id, item_type, level, generator_model, generated_at) values ('goi_bunpou_J2_002', 'goi_bunpou', 'J2', 'claude-sonnet-5', '2026-10-10T20:05:52+00:00') on conflict (id) do update set item_type = excluded.item_type, level = excluded.level, generator_model = excluded.generator_model, generated_at = excluded.generated_at;

insert into items (id, bundle_id, item_type, level, seed_cell_id, setting, relation, function, channel, scene_id, speaker_role, listener_role, topic, stem, correct_index, explanation_ja, explanation_en, vocab_notes, documents, dialogue, narration_clip_id, model_p_correct) values ('82271f996c', 'goi_bunpou_J2_002', 'goi_bunpou', 'J2', 'email_external+staff_to_customer+causative_permission@J2', 'email_external', 'staff_to_customer', 'causative_permission', 'written', null, null, null, '納品日変更の許可を顧客に依頼する', '誠に勝手なお願いで恐縮ですが、納品日を来週月曜日に変更＿＿＿よろしいでしょうか。', 2, '自社の都合で納品日を変更するという行為について、相手の許可を得る丁重な言い方が「させていただく」である。「していただいて」は相手に行為をしてもらう向きになり、変更する主体が逆になってしまう。「させてもらって」は実在する表現だが話し言葉的で、顧客あてのメールの丁重さにそぐわない。「させてもらわせて」は使役と受益表現を不自然に重ねた、存在しない形である。', 'させていただいて politely asks the customer''s permission for the company''s own action of changing the date; していただいて reverses the direction, させてもらって is too casual for a formal customer email, and させてもらわせて is not a real form.', '[{"term": "させていただく", "reading": "させていただく", "meaning": "humble causative-benefactive form used to ask permission for one''s own action"}, {"term": "納品日", "reading": "のうひんび", "meaning": "delivery date"}, {"term": "勝手なお願い", "reading": "かってなおねがい", "meaning": "a self-serving request (humble apology for inconvenience caused)"}]', '[]', '[]', null, 0.62) on conflict (id) do update set bundle_id = excluded.bundle_id, item_type = excluded.item_type, level = excluded.level, seed_cell_id = excluded.seed_cell_id, setting = excluded.setting, relation = excluded.relation, function = excluded.function, channel = excluded.channel, scene_id = excluded.scene_id, speaker_role = excluded.speaker_role, listener_role = excluded.listener_role, topic = excluded.topic, stem = excluded.stem, correct_index = excluded.correct_index, explanation_ja = excluded.explanation_ja, explanation_en = excluded.explanation_en, vocab_notes = excluded.vocab_notes, documents = excluded.documents, dialogue = excluded.dialogue, narration_clip_id = excluded.narration_clip_id, model_p_correct = excluded.model_p_correct;

-- Options are replaced wholesale rather than upserted: a corrected item can
-- have fewer options or a different order, and a stale row left behind would
-- be a fifth answer nobody meant to publish.
delete from item_options where item_id in ('82271f996c');
insert into item_options (item_id, position, text, role, why, clip_id) values ('82271f996c', 0, 'させてもらわせて', 'nonexistent_form', '「させてもらう」にさらに使役の「〜せる」を重ねたような形で、実際にはこのような活用は存在しない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('82271f996c', 1, 'していただいて', 'opposite_valence', '「していただく」は相手に行為をしてもらう向きの表現で、ここでは納品日を変更するのは自社側なので主語の向きが逆になる。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('82271f996c', 2, 'させていただいて', 'correct', '自社側の都合で変更するという行為を、相手の許可を得る形で丁重に述べる言い方で、「〜てよろしいでしょうか」と自然に続く。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('82271f996c', 3, 'させてもらって', 'real_form_wrong_context', '「させてもらう」自体は実際に使う表現だが、くだけた言い方で、顧客あてのメール文の丁重さには合わない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;

