-- goi_bunpou_J3_002: 1 × goi_bunpou (J3)
-- generated 2026-10-10T20:06:23+00:00 by claude-sonnet-5
-- Produced by bjt publish. Idempotent: re-running replaces these rows.

insert into bundles (id, item_type, level, generator_model, generated_at) values ('goi_bunpou_J3_002', 'goi_bunpou', 'J3', 'claude-sonnet-5', '2026-10-10T20:06:23+00:00') on conflict (id) do update set item_type = excluded.item_type, level = excluded.level, generator_model = excluded.generator_model, generated_at = excluded.generated_at;

insert into items (id, bundle_id, item_type, level, seed_cell_id, setting, relation, function, channel, scene_id, speaker_role, listener_role, topic, stem, correct_index, explanation_ja, explanation_en, vocab_notes, documents, dialogue, narration_clip_id, model_p_correct) values ('15061dc336', 'goi_bunpou_J3_002', 'goi_bunpou', 'J3', 'quote_document+staff_to_visitor+letter_set_phrase@J3', 'quote_document', 'staff_to_visitor', 'letter_set_phrase', 'written', null, null, null, '見積書を添付して送付する', 'ご依頼いただきました見積書を添付いたしましたので、＿＿＿のほどよろしくお願い申し上げます。', 0, '添付した書類を確認のうえ受け取ってほしいと伝える場面では「ご査収」が定型表現として使われる。「ご検収」は納品物を検査して正式に受け入れる場面で使う語であり、見積書の確認を依頼するこの文脈には合わない。「ご査受」はそれらしく見えるが実際には使われない言い方である。「ご笑納」は贈答品を受け取ってもらう際に使う表現で、事務文書である見積書には不適切。', 'ご査収 is the set phrase for asking someone to check and receive an attached document; ご検収 is for formally accepting delivered goods, ご査受 is not an actual term, and ご笑納 is used for gifts.', '[{"term": "ご査収", "reading": "ごさしゅう", "meaning": "please check and accept (the enclosed document)"}, {"term": "ご検収", "reading": "ごけんしゅう", "meaning": "formal inspection and acceptance of delivered goods"}, {"term": "ご笑納", "reading": "ごしょうのう", "meaning": "please kindly accept (a gift), humble expression"}]', '[]', '[]', null, 0.96) on conflict (id) do update set bundle_id = excluded.bundle_id, item_type = excluded.item_type, level = excluded.level, seed_cell_id = excluded.seed_cell_id, setting = excluded.setting, relation = excluded.relation, function = excluded.function, channel = excluded.channel, scene_id = excluded.scene_id, speaker_role = excluded.speaker_role, listener_role = excluded.listener_role, topic = excluded.topic, stem = excluded.stem, correct_index = excluded.correct_index, explanation_ja = excluded.explanation_ja, explanation_en = excluded.explanation_en, vocab_notes = excluded.vocab_notes, documents = excluded.documents, dialogue = excluded.dialogue, narration_clip_id = excluded.narration_clip_id, model_p_correct = excluded.model_p_correct;

-- Options are replaced wholesale rather than upserted: a corrected item can
-- have fewer options or a different order, and a stale row left behind would
-- be a fifth answer nobody meant to publish.
delete from item_options where item_id in ('15061dc336');
insert into item_options (item_id, position, text, role, why, clip_id) values ('15061dc336', 0, 'ご査収', 'correct', '送付した書類を相手に確認のうえ受け取ってもらう際の定型表現で、見積書を添付する文に自然に続く。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('15061dc336', 1, 'ご検収', 'real_form_wrong_context', '「ご検収」は納品された商品や成果物を検査したうえで正式に受け入れる場面で使う語で、見積書を確認してもらうだけのこの場面には重すぎる。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('15061dc336', 2, 'ご査受', 'nonexistent_form', '「査収」と「受領」を組み合わせたような語感だが、実際のビジネス文書でこのような言い方はされない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('15061dc336', 3, 'ご笑納', 'set_phrase_misfit', '「ご笑納」は贈り物を謙遜して受け取ってもらう際の表現で、見積書のような事務文書には使わない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;

