-- hatsugen_choukai_J1_002: 1 × hatsugen_choukai (J1)
-- generated 2026-10-05T22:43:45+00:00 by claude-sonnet-5
-- Produced by bjt publish. Idempotent: re-running replaces these rows.

-- Scenes are a shared bank (or, for 画像把握, one picture per item),
-- image_path stays null until the art exists, and is deliberately not
-- overwritten by a re-publish.
insert into scenes (id, label_ja) values ('scene_phone_desk', 'デスクで固定電話') on conflict (id) do update set label_ja = excluded.label_ja;

-- One row per distinct utterance. audio_path is filled in by the TTS step.
insert into audio_clips (id, text, voice, channel) values ('02cc5bc1ff5266a6', '営業部の社員が、経理部の同僚に内線で電話をかけました。経費精算のやり方で分からないことがあり、相談したいと思っています。こんなとき、何と言いますか。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('25c7c1a4fbc76235', 'いち', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('cce827953218fa41', 'もしもし、営業部の山田です。今ちょっといいですか。経費精算のことで相談したいんですが。', 'staff_mid_f', 'phone') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('6e34bf5479a4824e', 'に', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('e7e048840c6878ab', 'お忙しいところ恐れ入りますが、経費精算の件につきましてご教示賜れますと幸いに存じます。', 'staff_mid_f', 'phone') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('a94822f17a881031', 'さん', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('4e1cdff413a2748f', 'ねえ、経費精算のことなんだけど、ちょっと教えてくれない?', 'staff_mid_f', 'phone') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('5577d7cacee29a6c', 'よん', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('68608c139c423abb', 'あのさ、経費精算のやり方が全然わかんなくてさ、助けてよ。', 'staff_mid_f', 'phone') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;

insert into bundles (id, item_type, level, generator_model, generated_at) values ('hatsugen_choukai_J1_002', 'hatsugen_choukai', 'J1', 'claude-sonnet-5', '2026-10-05T22:43:45+00:00') on conflict (id) do update set item_type = excluded.item_type, level = excluded.level, generator_model = excluded.generator_model, generated_at = excluded.generated_at;

insert into items (id, bundle_id, item_type, level, seed_cell_id, setting, relation, function, channel, scene_id, speaker_role, listener_role, topic, stem, correct_index, explanation_ja, explanation_en, vocab_notes, documents, dialogue, narration_clip_id, model_p_correct) values ('fe23b1473d', 'hatsugen_choukai_J1_002', 'hatsugen_choukai', 'J1', 'phone_internal+peer_to_peer+consult@J1', 'phone_internal', 'peer_to_peer', 'consult', 'phone', 'scene_phone_desk', '営業部の社員', '経理部の同僚', '経費精算のやり方について同僚に相談する', '営業部の社員が、経理部の同僚に内線で電話をかけました。経費精算のやり方で分からないことがあり、相談したいと思っています。こんなとき、何と言いますか。', 0, '同僚への内線電話では、まず部署名と名前を名乗り、そのうえで用件を簡潔に伝えるのが基本の型である。正解はこの型を満たしており、相談したいという意図も明確である。名乗りを省いて用件から入る言い方は、電話を受けた相手が発信者を認識できず、内線電話の基本を欠く。くだけすぎた話し方は同僚相手でも業務連絡としての丁寧さが不足する。「ご教示賜れますと幸いに存じます」は取引先向けの改まった表現であり、同じ社内の同僚への相談としては過剰で場違いである。', 'An internal call to a colleague needs a name-and-department greeting followed by a concise request; skipping the greeting, using overly casual slang, or using client-grade formal keigo on a peer all fail.', '[{"term": "内線", "reading": "ないせん", "meaning": "internal extension line (within the same company)"}, {"term": "ご教示賜れますと幸いに存じます", "reading": "ごきょうじたまわれますとさいわいにぞんじます", "meaning": "a very formal written-style request for guidance, typically used toward clients, not peers"}]', '[]', '[]', '02cc5bc1ff5266a6', 0.86) on conflict (id) do update set bundle_id = excluded.bundle_id, item_type = excluded.item_type, level = excluded.level, seed_cell_id = excluded.seed_cell_id, setting = excluded.setting, relation = excluded.relation, function = excluded.function, channel = excluded.channel, scene_id = excluded.scene_id, speaker_role = excluded.speaker_role, listener_role = excluded.listener_role, topic = excluded.topic, stem = excluded.stem, correct_index = excluded.correct_index, explanation_ja = excluded.explanation_ja, explanation_en = excluded.explanation_en, vocab_notes = excluded.vocab_notes, documents = excluded.documents, dialogue = excluded.dialogue, narration_clip_id = excluded.narration_clip_id, model_p_correct = excluded.model_p_correct;

-- Options are replaced wholesale rather than upserted: a corrected item can
-- have fewer options or a different order, and a stale row left behind would
-- be a fifth answer nobody meant to publish.
delete from item_options where item_id in ('fe23b1473d');
insert into item_options (item_id, position, text, role, why, clip_id) values ('fe23b1473d', 0, 'もしもし、営業部の山田です。今ちょっといいですか。経費精算のことで相談したいんですが。', 'correct', '内線電話の型どおり部署名と名前を名乗ったうえで、相談したいという用件を簡潔に伝えており、同僚への依頼として過不足がない。', 'cce827953218fa41') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('fe23b1473d', 1, 'お忙しいところ恐れ入りますが、経費精算の件につきましてご教示賜れますと幸いに存じます。', 'over_polite_misfit', '「ご教示賜れますと幸いに存じます」は取引先に向けるような改まった敬語で、同じ社内の同僚に使うには堅すぎて不自然に響く。', 'e7e048840c6878ab') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('fe23b1473d', 2, 'ねえ、経費精算のことなんだけど、ちょっと教えてくれない?', 'phone_protocol_violation', '名乗りを省いていきなり用件に入っており、内線でも相手が誰からの電話か分からず、社内電話の基本の型を欠いている。', '4e1cdff413a2748f') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('fe23b1473d', 3, 'あのさ、経費精算のやり方が全然わかんなくてさ、助けてよ。', 'register_too_casual', '名乗りもなく「わかんなくてさ」「助けてよ」とくだけすぎており、同僚相手でも業務の電話としての丁寧さを欠いている。', '68608c139c423abb') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;

