-- hyougen_J2_002: 1 × hyougen (J2)
-- generated 2026-10-04T19:40:28+00:00 by claude-sonnet-5
-- Produced by bjt publish. Idempotent: re-running replaces these rows.

insert into bundles (id, item_type, level, generator_model, generated_at) values ('hyougen_J2_002', 'hyougen', 'J2', 'claude-sonnet-5', '2026-10-04T19:40:28+00:00') on conflict (id) do update set item_type = excluded.item_type, level = excluded.level, generator_model = excluded.generator_model, generated_at = excluded.generated_at;

insert into items (id, bundle_id, item_type, level, seed_cell_id, setting, relation, function, channel, scene_id, speaker_role, listener_role, topic, stem, correct_index, explanation_ja, explanation_en, vocab_notes, documents, dialogue, narration_clip_id, model_p_correct) values ('9dd57c3533', 'hyougen_J2_002', 'hyougen', 'J2', 'video_call+peer_to_peer+chair_meeting@J2', 'video_call', 'peer_to_peer', 'chair_meeting', 'video', null, null, null, 'オンライン会議で同僚が議論を整理して進行する', '同僚同士のオンライン会議で、議論が長引いています。進行役を務める立場として、意見を整理し次の話題に移りたいとき、最も適切な表現はどれですか。', 3, '議論を整理して次に進める進行役の発言は、出た意見を要約し、次に話す内容を具体的に示す形にする。「まとめさせていただいてもよろしいでしょうか」は敬語としては正しいが、対等な同僚間の進行をわざわざ許可を求める行為に変えてしまい、話が進まない。「もうこの話終わりでいいよね」はくだけすぎて会議の進行発言としての体裁がない。「申し上げていただけますか」は謙譲語である「申し上げる」を相手の行為に向けており、敬意の向きが逆になっている。', 'A peer facilitator summarizes the discussion and names the next topic directly, without turning facilitation into a permission request, using casual slang, or misdirecting humble language at the listener.', '[{"term": "進行役", "reading": "しんこうやく", "meaning": "meeting facilitator"}, {"term": "絞れる", "reading": "しぼれる", "meaning": "to be narrowed down (options)"}, {"term": "申し上げる", "reading": "もうしあげる", "meaning": "humble form of ''to say'' (used for one''s own speech)"}]', '[]', '[]', null, 0.93) on conflict (id) do update set bundle_id = excluded.bundle_id, item_type = excluded.item_type, level = excluded.level, seed_cell_id = excluded.seed_cell_id, setting = excluded.setting, relation = excluded.relation, function = excluded.function, channel = excluded.channel, scene_id = excluded.scene_id, speaker_role = excluded.speaker_role, listener_role = excluded.listener_role, topic = excluded.topic, stem = excluded.stem, correct_index = excluded.correct_index, explanation_ja = excluded.explanation_ja, explanation_en = excluded.explanation_en, vocab_notes = excluded.vocab_notes, documents = excluded.documents, dialogue = excluded.dialogue, narration_clip_id = excluded.narration_clip_id, model_p_correct = excluded.model_p_correct;

-- Options are replaced wholesale rather than upserted: a corrected item can
-- have fewer options or a different order, and a stale row left behind would
-- be a fifth answer nobody meant to publish.
delete from item_options where item_id in ('9dd57c3533');
insert into item_options (item_id, position, text, role, why, clip_id) values ('9dd57c3533', 0, 'みなさんのご意見を申し上げていただけますか。', 'wrong_honorific_direction', '「申し上げる」は自分の行為をへりくだる謙譲語で、相手の発言を促す表現に使うと敬意の向きが逆になる。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('9dd57c3533', 1, 'もうこの話終わりでいいよね、次行こう。', 'register_too_casual', '内容としては進行だが、オンライン会議という場での発言として崩れすぎており、議論をまとめる説明もない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('9dd57c3533', 2, '恐れ入りますが、ここまでの意見をまとめさせていただいてもよろしいでしょうか。', 'correct_keigo_wrong_speech_act', '敬語は整っているが、対等な同僚同士の会議で進行という本来の行為まで許可を求める形にしており、話が前に進まない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('9dd57c3533', 3, 'ここまでの意見をまとめると、A案とB案に絞れそうですね。次はコストも含めて比較していきましょうか。', 'correct', '出た意見を簡潔に整理し、次に話す内容を具体的に示しており、同僚同士の進行役として自然な切り替え方になっている。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;

