-- shiryou_choudokkai_J1_002: 3 × shiryou_choudokkai (J1)
-- generated 2026-10-02T04:41:14+00:00 by claude-sonnet-5
-- Produced by bjt publish. Idempotent: re-running replaces these rows.

-- Scenes are a shared bank (or, for 画像把握, one picture per item),
-- image_path stays null until the art exists, and is deliberately not
-- overwritten by a re-publish.
insert into scenes (id, label_ja) values ('scene_phone_desk', 'デスクで固定電話') on conflict (id) do update set label_ja = excluded.label_ja;

-- One row per distinct utterance. audio_path is filled in by the TTS step.
insert into audio_clips (id, text, voice, channel) values ('868403b9d7b9834c', '後輩が予定表を見ながら電話でこう言いました。「先輩、十五日の予定なんですが、第一応接室にB社商談と定例会議が両方入っているように見えます。」先輩は「ああ、B社商談は仮予約のままだったので、空いていた第二応接室に変更しました。定例会議は予定通り第一応接室で行います」と答えました。B社商談は十五日、どこで行われますか。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('e25a16407ece390d', '取引先からの確認メールを見ながら、部下が電話でこう報告しました。「さきほど先方に確認しましたところ、継手金具Bの単価は480円ではなく520円に訂正するとのことでした。金具Aの単価は変更ありません。」上司は、今回の注文の合計金額をいくらだと理解すればよいですか。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('48b2cfd9d9fb7775', '予定表を見ながら電話を受けた後輩に、先輩がこう言いました。「有明商事の件だけど、仮予約だった会議室が先方から正式に決まったって連絡があったんだ。第一会議室じゃなくて、第三会議室になったから。時間はそのまま変わらないよ。」10月16日の訪問はどこで行うことになりましたか。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;

insert into bundles (id, item_type, level, generator_model, generated_at) values ('shiryou_choudokkai_J1_002', 'shiryou_choudokkai', 'J1', 'claude-sonnet-5', '2026-10-02T04:41:14+00:00') on conflict (id) do update set item_type = excluded.item_type, level = excluded.level, generator_model = excluded.generator_model, generated_at = excluded.generated_at;

insert into items (id, bundle_id, item_type, level, seed_cell_id, setting, relation, function, channel, scene_id, speaker_role, listener_role, topic, stem, correct_index, explanation_ja, explanation_en, vocab_notes, documents, dialogue, narration_clip_id, model_p_correct) values ('8091994664', 'shiryou_choudokkai_J1_002', 'shiryou_choudokkai', 'J1', 'schedule_sheet+junior_to_senior+find_the_conflict@J1', 'schedule_sheet', 'junior_to_senior', 'find_the_conflict', 'phone', null, null, null, '予定表の重複予約を電話で確認する', '後輩が予定表を見ながら電話でこう言いました。「先輩、十五日の予定なんですが、第一応接室にB社商談と定例会議が両方入っているように見えます。」先輩は「ああ、B社商談は仮予約のままだったので、空いていた第二応接室に変更しました。定例会議は予定通り第一応接室で行います」と答えました。B社商談は十五日、どこで行われますか。', 3, '予定表では15日の第一応接室にB社商談（仮予約）と定例会議が重なって記載されている。電話で先輩は、仮予約だったB社商談を空いていた第二応接室に変更したと説明し、定例会議は第一応接室のままだと述べた。予定表だけでは重複していることは分かるが変更後の場所は分からず、電話だけでは何が変更されたのか特定できない。第一応接室は変更前の値、第三応接室は別の日の別の行、第二会議室は語の一部が似ているだけの無関係な部屋であり、いずれも誤り。', 'The schedule shows a room conflict on the 15th; the phone call reveals which event was moved and to where, requiring both sources.', '[{"term": "仮予約", "reading": "かりよやく", "meaning": "provisional reservation"}, {"term": "応接室", "reading": "おうせつしつ", "meaning": "reception/meeting room"}]', '[{"template": "schedule", "title": "来客対応・会議室予定表", "meta": [{"label": "期間", "value": "10月14日〜10月16日"}, {"label": "作成者", "value": "営業部 佐藤"}], "blocks": [{"type": "table", "columns": ["日付", "内容", "場所", "担当"], "rows": [["10月14日", "A社訪問", "第二応接室", "木村"], ["10月15日", "B社商談", "第一応接室（仮予約）", "森田"], ["10月15日", "社内定例会議", "第一応接室", "佐藤"], ["10月16日", "C社訪問", "第三応接室", "木村"]]}]}]', '[]', '868403b9d7b9834c', 1.0) on conflict (id) do update set bundle_id = excluded.bundle_id, item_type = excluded.item_type, level = excluded.level, seed_cell_id = excluded.seed_cell_id, setting = excluded.setting, relation = excluded.relation, function = excluded.function, channel = excluded.channel, scene_id = excluded.scene_id, speaker_role = excluded.speaker_role, listener_role = excluded.listener_role, topic = excluded.topic, stem = excluded.stem, correct_index = excluded.correct_index, explanation_ja = excluded.explanation_ja, explanation_en = excluded.explanation_en, vocab_notes = excluded.vocab_notes, documents = excluded.documents, dialogue = excluded.dialogue, narration_clip_id = excluded.narration_clip_id, model_p_correct = excluded.model_p_correct;
insert into items (id, bundle_id, item_type, level, seed_cell_id, setting, relation, function, channel, scene_id, speaker_role, listener_role, topic, stem, correct_index, explanation_ja, explanation_en, vocab_notes, documents, dialogue, narration_clip_id, model_p_correct) values ('753c57209e', 'shiryou_choudokkai_J1_002', 'shiryou_choudokkai', 'J1', 'delivery_email+subordinate_to_superior+find_the_conflict@J1', 'delivery_email', 'subordinate_to_superior', 'find_the_conflict', 'phone', null, null, null, '納品確認メールの単価訂正', '取引先からの確認メールを見ながら、部下が電話でこう報告しました。「さきほど先方に確認しましたところ、継手金具Bの単価は480円ではなく520円に訂正するとのことでした。金具Aの単価は変更ありません。」上司は、今回の注文の合計金額をいくらだと理解すればよいですか。', 0, 'メールの合計142,000円は単価480円を前提にした数字だが、電話でBの単価が520円に訂正されたと伝えられたため、Bの金額を78,000円に直して計算し直す必要がある。Aは70,000円のままなので、正しい合計は148,000円。142,000円はメールの数字をそのまま使った誤り、176,000円は訂正をAの行に誤って当てはめた誤り、83,000円は来月分の見込み額であり今回の注文額ではない。メールだけでは訂正の事実が分からず、電話だけではAとBの元の金額が分からないため、両方の情報が必要になる。', 'The email''s total assumes the old unit price; the call revises only item B''s price, so the total must be recalculated using the email''s figures for A and the corrected figure for B.', '[{"term": "単価", "reading": "たんか", "meaning": "unit price"}, {"term": "据え置き", "reading": "すえおき", "meaning": "kept unchanged"}, {"term": "月末締め翌月末払い", "reading": "げつまつじめよくげつまつばらい", "meaning": "payment terms: closed at month-end, paid at the end of the following month"}]', '[{"template": "email_external", "title": "発注No.245 ご注文の確認", "meta": [{"label": "差出人", "value": "さくら精密株式会社 営業部 中村"}, {"label": "宛先", "value": "山川商事株式会社 資材部 佐藤様"}, {"label": "件名", "value": "発注No.245 ご注文の確認"}, {"label": "日時", "value": "9月10日 11時"}], "blocks": [{"type": "paragraph", "text": "いつもお世話になっております。ご注文いただきました商品について、下記のとおりご確認申し上げます。"}, {"type": "table", "caption": "ご注文内容", "columns": ["品目", "数量", "単価", "金額"], "rows": [["継手金具A", "200個", "350円", "70,000円"], ["継手金具B", "150個", "480円", "72,000円"]]}, {"type": "key_values", "pairs": [{"label": "合計金額", "value": "142,000円"}, {"label": "支払条件", "value": "月末締め翌月末払い"}]}]}]', '[]', 'e25a16407ece390d', 1.0) on conflict (id) do update set bundle_id = excluded.bundle_id, item_type = excluded.item_type, level = excluded.level, seed_cell_id = excluded.seed_cell_id, setting = excluded.setting, relation = excluded.relation, function = excluded.function, channel = excluded.channel, scene_id = excluded.scene_id, speaker_role = excluded.speaker_role, listener_role = excluded.listener_role, topic = excluded.topic, stem = excluded.stem, correct_index = excluded.correct_index, explanation_ja = excluded.explanation_ja, explanation_en = excluded.explanation_en, vocab_notes = excluded.vocab_notes, documents = excluded.documents, dialogue = excluded.dialogue, narration_clip_id = excluded.narration_clip_id, model_p_correct = excluded.model_p_correct;
insert into items (id, bundle_id, item_type, level, seed_cell_id, setting, relation, function, channel, scene_id, speaker_role, listener_role, topic, stem, correct_index, explanation_ja, explanation_en, vocab_notes, documents, dialogue, narration_clip_id, model_p_correct) values ('0c99e55bd7', 'shiryou_choudokkai_J1_002', 'shiryou_choudokkai', 'J1', 'schedule_sheet+junior_to_senior+apply_spoken_change@J1', 'schedule_sheet', 'junior_to_senior', 'apply_spoken_change', 'phone', 'scene_phone_desk', null, null, '訪問先の会議室が仮予約から確定する', '予定表を見ながら電話を受けた後輩に、先輩がこう言いました。「有明商事の件だけど、仮予約だった会議室が先方から正式に決まったって連絡があったんだ。第一会議室じゃなくて、第三会議室になったから。時間はそのまま変わらないよ。」10月16日の訪問はどこで行うことになりましたか。', 3, '予定表では10月16日の有明商事訪問の場所は「第一会議室（仮予約）」となっているが、電話で先輩が「仮予約が正式に決まり、第三会議室になった」と伝えている。したがって答えは第三会議室。第一会議室は変更前の資料の記載をそのまま採用した誤り、第二会議室は別の日（15日・17日）に使う弊社の会議室を混同したもの、応接室は既に済んだ14日の訪問先で、時系列を取り違えている。資料だけでは仮予約がどうなったか分からず、電話だけではどの訪問の話か分からない。', 'The schedule lists the October 16 room as provisional; the call confirms it changed from Room 1 to Room 3, so only combining both sources gives the answer.', '[{"term": "仮予約", "reading": "かりよやく", "meaning": "provisional reservation"}, {"term": "正式に決まる", "reading": "せいしきにきまる", "meaning": "to be formally confirmed"}, {"term": "応接室", "reading": "おうせつしつ", "meaning": "reception room"}]', '[{"template": "schedule", "title": "10月 得意先訪問予定表", "meta": [{"label": "期間", "value": "10月14日（月）〜10月18日（金）"}, {"label": "作成者", "value": "営業部 木村"}], "blocks": [{"type": "table", "columns": ["日付", "訪問先", "時間", "場所"], "rows": [["10月14日（月）", "さくら物産", "13時〜14時", "先方本社3階 応接室"], ["10月15日（火）", "高橋精密", "10時〜11時", "弊社 第二会議室"], ["10月16日（水）", "有明商事", "14時〜15時", "先方本社 第一会議室（仮予約）"], ["10月17日（木）", "緑川工業", "11時〜12時", "弊社 第二会議室"], ["10月18日（金）", "高橋精密", "15時〜16時", "先方本社 応接室"]]}]}]', '[]', '48b2cfd9d9fb7775', 1.0) on conflict (id) do update set bundle_id = excluded.bundle_id, item_type = excluded.item_type, level = excluded.level, seed_cell_id = excluded.seed_cell_id, setting = excluded.setting, relation = excluded.relation, function = excluded.function, channel = excluded.channel, scene_id = excluded.scene_id, speaker_role = excluded.speaker_role, listener_role = excluded.listener_role, topic = excluded.topic, stem = excluded.stem, correct_index = excluded.correct_index, explanation_ja = excluded.explanation_ja, explanation_en = excluded.explanation_en, vocab_notes = excluded.vocab_notes, documents = excluded.documents, dialogue = excluded.dialogue, narration_clip_id = excluded.narration_clip_id, model_p_correct = excluded.model_p_correct;

-- Options are replaced wholesale rather than upserted: a corrected item can
-- have fewer options or a different order, and a stale row left behind would
-- be a fifth answer nobody meant to publish.
delete from item_options where item_id in ('8091994664', '753c57209e', '0c99e55bd7');
insert into item_options (item_id, position, text, role, why, clip_id) values ('8091994664', 0, '第二会議室', 'surface_keyword_match', '「第二」という語は共通するが、予定表にも会話にも登場しない部屋であり、実際の変更先である第二応接室とは異なる。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('8091994664', 1, '第三応接室', 'reads_wrong_row', '16日のC社訪問で使われる部屋であり、15日のB社商談とは別の行の情報。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('8091994664', 2, '第一応接室', 'ignores_the_spoken_change', '予定表に元々書かれていた場所で、電話で変更が伝えられたことを反映していない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('8091994664', 3, '第二応接室', 'correct', '先輩の説明どおり、仮予約だったB社商談は実際に空いていた第二応接室に変更されたため。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('753c57209e', 0, '148,000円', 'correct', 'Aは70,000円のまま、Bを150個×520円の78,000円に直して合計すると148,000円になる。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('753c57209e', 1, '142,000円', 'ignores_the_spoken_change', 'メールに書かれた元の単価480円のままの合計で、電話で伝えられた520円への訂正が反映されていない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('753c57209e', 2, '83,000円', 'wrong_timeframe', 'これは来月の追加発注分の見込み合計であり、今回すでに確定している今月分の注文額ではない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('753c57209e', 3, '176,000円', 'reads_wrong_row', '単価の訂正をAの行に当てはめて計算した数字で、実際に訂正されたのはBの単価であってAではない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('0c99e55bd7', 0, '第二会議室', 'reads_wrong_row', '15日と17日の弊社での訪問で使われる会議室で、16日の有明商事の行ではない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('0c99e55bd7', 1, '第一会議室', 'ignores_the_spoken_change', '資料に記載された仮予約時点の場所のままで、電話で伝えられた変更を反映していない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('0c99e55bd7', 2, '先方本社3階 応接室', 'wrong_timeframe', '14日のさくら物産訪問で使われた場所で、電話の時点ですでに終わっている過去の訪問先である。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('0c99e55bd7', 3, '第三会議室', 'correct', '仮予約だった第一会議室から、先方の正式決定により変更された場所である。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;

-- Withdrawn after review: batches/withdrawn.txt says why. An unpublish,
-- never a delete, so every answer already given keeps resolving. Nothing
-- here ever sets is_published back to 1: a question the owner vetoed
-- in the app stays vetoed however often this file is applied.
update items set is_published = 0
 where id in ('0c99e55bd7');

