-- sougou_dokkai_J3_002: 1 × sougou_dokkai (J3)
-- generated 2026-10-02T21:42:50+00:00 by claude-sonnet-5
-- Produced by bjt publish. Idempotent: re-running replaces these rows.

insert into bundles (id, item_type, level, generator_model, generated_at) values ('sougou_dokkai_J3_002', 'sougou_dokkai', 'J3', 'claude-sonnet-5', '2026-10-02T21:42:50+00:00') on conflict (id) do update set item_type = excluded.item_type, level = excluded.level, generator_model = excluded.generator_model, generated_at = excluded.generated_at;

insert into items (id, bundle_id, item_type, level, seed_cell_id, setting, relation, function, channel, scene_id, speaker_role, listener_role, topic, stem, correct_index, explanation_ja, explanation_en, vocab_notes, documents, dialogue, narration_clip_id, model_p_correct) values ('086fc7d264', 'sougou_dokkai_J3_002', 'sougou_dokkai', 'J3', 'internal_change+junior_to_senior+infer_owner@J3', 'internal_change', 'junior_to_senior', 'infer_owner', 'written', null, null, null, '消耗品発注ルール変更の訂正対応', 'この通知によると、営業部で消耗品が足りなくなったとき、誰が発注の手続きをしますか。', 0, '通知はまず当初のルール（全部署がシステムで発注）を示したあと、訂正として営業部だけは従来どおり総務部へメールで依頼する形を続けると定めている。したがって営業部の発注は、総務部が依頼を受けて行う。システム発注や毎月25日の締め切りは他部署の話で、営業部には当てはまらない。システム管理者という役割はそもそも文書に存在しない。', 'The revision carves out Sales from the new system-based ordering, so General Affairs still handles their requests by email; the system rule and deadline belong to the other departments.', '[{"term": "一括", "reading": "いっかつ", "meaning": "all at once, in a lump"}, {"term": "不慣れ", "reading": "ふなれ", "meaning": "unaccustomed, unfamiliar"}]', '[{"template": "memo_notice", "title": "消耗品発注ルールの変更について（訂正）", "meta": [{"label": "発信者", "value": "総務部"}, {"label": "発信日", "value": "9月28日"}, {"label": "対象", "value": "全社員"}], "blocks": [{"type": "heading", "text": "当初のお知らせ（9月20日発信分）", "level": 2}, {"type": "paragraph", "text": "10月1日より、消耗品（文房具・コピー用紙等）の発注方法を次のとおり変更します。これまで総務部が一括で発注していましたが、今後は各部署の発注担当者が、社内システム「よろずくん」から直接発注してください。締め切りは毎月25日です。"}, {"type": "heading", "text": "訂正のお知らせ", "level": 2}, {"type": "paragraph", "text": "上記について、一部訂正いたします。営業部は人数が少なく、システムの操作に不慣れな方も多いため、従来どおり総務部へメールで依頼する形を続けます。システムでの発注は不要です。その他の部署は、予定どおり10月1日からシステムでの発注に切り替えてください。"}, {"type": "callout", "text": "営業部の方は、消耗品が必要になった際、品目と数量を記載のうえ総務部（soumu@asahi-kogyo.co.jp）宛にメールしてください。", "tone": "action"}]}]', '[]', null, 1.0) on conflict (id) do update set bundle_id = excluded.bundle_id, item_type = excluded.item_type, level = excluded.level, seed_cell_id = excluded.seed_cell_id, setting = excluded.setting, relation = excluded.relation, function = excluded.function, channel = excluded.channel, scene_id = excluded.scene_id, speaker_role = excluded.speaker_role, listener_role = excluded.listener_role, topic = excluded.topic, stem = excluded.stem, correct_index = excluded.correct_index, explanation_ja = excluded.explanation_ja, explanation_en = excluded.explanation_en, vocab_notes = excluded.vocab_notes, documents = excluded.documents, dialogue = excluded.dialogue, narration_clip_id = excluded.narration_clip_id, model_p_correct = excluded.model_p_correct;

-- Options are replaced wholesale rather than upserted: a corrected item can
-- have fewer options or a different order, and a stale row left behind would
-- be a fifth answer nobody meant to publish.
delete from item_options where item_id in ('086fc7d264');
insert into item_options (item_id, position, text, role, why, clip_id) values ('086fc7d264', 0, '総務部の担当者が、営業部からのメール依頼を受けて発注する。', 'correct', '訂正のお知らせで、営業部は従来どおり総務部へメールで依頼する形を続けると明記されている。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('086fc7d264', 1, '営業部の発注担当者が、10月1日から社内システム「よろずくん」で発注する。', 'wrong_timeframe', 'これは9月20日の当初の通知の内容で、その後の訂正により営業部はシステム発注の対象から外れている。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('086fc7d264', 2, 'システム管理者が、営業部の発注を代行して入力する。', 'surface_keyword_match', '通知に「システム」という語は出てくるが、営業部の発注はシステムではなくメール依頼の形を続けることになっており、システム管理者という役割も登場しない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('086fc7d264', 3, '各部署の発注担当者が、毎月25日までに社内システムで発注する。', 'stated_but_answers_different_question', '他の部署には当てはまる規定だが、営業部は訂正で除外されているため、この問いの答えにはならない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;

