-- sougou_choudokkai_J1_002: 3 × sougou_choudokkai (J1)
-- generated 2026-10-02T04:41:14+00:00 by claude-sonnet-5
-- Produced by bjt publish. Idempotent: re-running replaces these rows.

-- Scenes are a shared bank (or, for 画像把握, one picture per item),
-- image_path stays null until the art exists, and is deliberately not
-- overwritten by a re-publish.
insert into scenes (id, label_ja) values ('scene_meeting_room_table', '社内の会議室のテーブル') on conflict (id) do update set label_ja = excluded.label_ja;
insert into scenes (id, label_ja) values ('scene_office_desk_pair', '自分の席で向かい合う二人') on conflict (id) do update set label_ja = excluded.label_ja;
insert into scenes (id, label_ja) values ('scene_video_call_laptop', 'ノートPCでオンライン会議') on conflict (id) do update set label_ja = excluded.label_ja;

-- One row per distinct utterance. audio_path is filled in by the TTS step.
insert into audio_clips (id, text, voice, channel) values ('c16863511b844dc7', 'データ移行の開始予定は、いつからになりましたか。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('2b02bce288b43518', 'この報告書の通り、データ移行は十月一日開始の予定でした。', 'manager_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('7afb4b86ec8df75b', 'テスト環境の構築が九月十五日に終わる予定でしたが、それは今どうなっていますか。', 'staff_junior_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('3e61351755a4c0b7', '先週ようやく完了しました。ただ、ベンダー側の人員不足で、データ移行の開始自体が一週間遅れて十月八日からになりました。', 'manager_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('894530015214ebfd', 'では、データ移行は九月十五日からということですね？', 'staff_junior_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('1febbc2c24f4b404', 'いえ、九月十五日はテスト環境の予定日です。データ移行の開始は十月八日です。', 'manager_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('9cdc1f38f6cd06a5', '承知しました。十月八日から準備します。', 'staff_junior_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('89720e51a9160978', '会場と仕出し業者は、結局どうなりましたか。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('ca8e43d4b5d3cad6', '議事録では会場はAホールに決まっていましたが、先週連絡があって、Aホールは改装工事で使えなくなったそうです。', 'manager_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('260597879e7e88df', 'それは困りますね。代わりの案はあるんですか。', 'staff_junior_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('0bf957ed219656f3', 'Bホールを押さえました。広さも予算内に収まります。', 'manager_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('28346885e5f18f68', '分かりました。仕出し業者はどうなりましたか。議事録では未定のままでしたが。', 'staff_junior_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('fd85153bd6e5a2f1', 'それは山田さんがX社に決めたと聞いています。', 'manager_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('11e96cb2010d343e', 'では、会場と仕出し、両方とも決まったということですね。', 'staff_junior_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('a4e7430667229af8', '研修当日の会場対応は、誰が行うことになりましたか。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('6c56f26bb38d3038', '議事録では、会場の予約と当日対応、それに昼食の手配まで、すべて中村さんになっていますね。', 'manager_m', 'video') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('d64533cf7fe8ccc5', 'はい。ただ、中村さんは来週から出張で、研修当日は不在の予定です。', 'staff_junior_m', 'video') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('e357a5e2ef1b42db', 'それは困りますね。予約はもう済んでいるようですが、当日対応は佐藤さんにお願いできますか。', 'manager_m', 'video') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('ef6bf54f12483df1', '承知しました。私が当日対応いたします。', 'staff_junior_m', 'video') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('6b2ab03f77832a05', '昼食の手配については、中村さんが出張前に済ませると言っていました。', 'staff_junior_m', 'video') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('e33a1f16704f607c', 'それはそのままで結構です。', 'manager_m', 'video') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;

insert into bundles (id, item_type, level, generator_model, generated_at) values ('sougou_choudokkai_J1_002', 'sougou_choudokkai', 'J1', 'claude-sonnet-5', '2026-10-02T04:41:14+00:00') on conflict (id) do update set item_type = excluded.item_type, level = excluded.level, generator_model = excluded.generator_model, generated_at = excluded.generated_at;

insert into items (id, bundle_id, item_type, level, seed_cell_id, setting, relation, function, channel, scene_id, speaker_role, listener_role, topic, stem, correct_index, explanation_ja, explanation_en, vocab_notes, documents, dialogue, narration_clip_id, model_p_correct) values ('23fd538a62', 'sougou_choudokkai_J1_002', 'sougou_choudokkai', 'J1', 'handover+other_department+reconcile_document@J1', 'handover', 'other_department', 'reconcile_document', 'in_person', 'scene_office_desk_pair', null, null, 'システム移行案件の引き継ぎ', 'データ移行の開始予定は、いつからになりましたか。', 1, '報告書ではデータ移行の開始予定は10月1日となっているが、会話でテスト環境構築の完了後、ベンダー側の人員不足によりデータ移行の開始自体が1週間遅れて10月8日になったと分かる。9月15日はテスト環境構築の予定日であり、経理部担当者が誤って結び付けたものをシステム部担当者が訂正している。10月15日はさらに遅れた場合の推測に過ぎず、根拠がない。報告書だけでは遅れが分からず、会話だけでは元の予定日が分からないため、両方を突き合わせないと正しい日付は選べない。', 'The report lists an original start date; the conversation reveals a one-week vendor delay that pushes it back, and a colleague''s misattributed date is corrected on the spot.', '[{"term": "検収", "reading": "けんしゅう", "meaning": "acceptance inspection"}, {"term": "人員不足", "reading": "じんいんぶそく", "meaning": "staff shortage"}, {"term": "引き継ぎ", "reading": "ひきつぎ", "meaning": "handover"}]', '[{"template": "progress_report", "title": "顧客管理システム移行 進捗報告書", "meta": [{"label": "報告者", "value": "システム部 保田"}, {"label": "報告日", "value": "9月20日"}, {"label": "案件", "value": "顧客管理システム移行（経理部向け）"}], "blocks": [{"type": "table", "caption": "作業マイルストーン", "columns": ["項目", "状況", "予定日"], "rows": [["要件定義", "完了", "8月31日"], ["テスト環境構築", "遅延中", "9月15日"], ["データ移行", "未着手", "10月1日開始"]]}]}]', '[{"speaker_role": "システム部担当者", "text": "この報告書の通り、データ移行は十月一日開始の予定でした。", "clip_id": "2b02bce288b43518"}, {"speaker_role": "経理部担当者", "text": "テスト環境の構築が九月十五日に終わる予定でしたが、それは今どうなっていますか。", "clip_id": "7afb4b86ec8df75b"}, {"speaker_role": "システム部担当者", "text": "先週ようやく完了しました。ただ、ベンダー側の人員不足で、データ移行の開始自体が一週間遅れて十月八日からになりました。", "clip_id": "3e61351755a4c0b7"}, {"speaker_role": "経理部担当者", "text": "では、データ移行は九月十五日からということですね？", "clip_id": "894530015214ebfd"}, {"speaker_role": "システム部担当者", "text": "いえ、九月十五日はテスト環境の予定日です。データ移行の開始は十月八日です。", "clip_id": "1febbc2c24f4b404"}, {"speaker_role": "経理部担当者", "text": "承知しました。十月八日から準備します。", "clip_id": "9cdc1f38f6cd06a5"}]', 'c16863511b844dc7', 1.0) on conflict (id) do update set bundle_id = excluded.bundle_id, item_type = excluded.item_type, level = excluded.level, seed_cell_id = excluded.seed_cell_id, setting = excluded.setting, relation = excluded.relation, function = excluded.function, channel = excluded.channel, scene_id = excluded.scene_id, speaker_role = excluded.speaker_role, listener_role = excluded.listener_role, topic = excluded.topic, stem = excluded.stem, correct_index = excluded.correct_index, explanation_ja = excluded.explanation_ja, explanation_en = excluded.explanation_en, vocab_notes = excluded.vocab_notes, documents = excluded.documents, dialogue = excluded.dialogue, narration_clip_id = excluded.narration_clip_id, model_p_correct = excluded.model_p_correct;
insert into items (id, bundle_id, item_type, level, seed_cell_id, setting, relation, function, channel, scene_id, speaker_role, listener_role, topic, stem, correct_index, explanation_ja, explanation_en, vocab_notes, documents, dialogue, narration_clip_id, model_p_correct) values ('2bb7e73bae', 'sougou_choudokkai_J1_002', 'sougou_choudokkai', 'J1', 'project_meeting+peer_to_peer+summarise_outcome@J1', 'project_meeting', 'peer_to_peer', 'summarise_outcome', 'in_person', 'scene_meeting_room_table', null, null, '新製品発表会の会場と業者決定', '会場と仕出し業者は、結局どうなりましたか。', 2, '議事録では会場はAホールに決定済み、仕出し業者は未定のまま次回検討とされていた。会話で、Aホールが改装工事のため使えなくなり同僚AがBホールを押さえたこと、仕出し業者は山田がX社に決めたことが分かる。議事録だけでは変更を知りえず、会話だけでは元の会場が分からないため、両方を突き合わせて初めて結論が定まる。combines_wrong_pairは会場だけ古い情報のまま、wrong_action_ownerは決定者を取り違え、stated_by_wrong_speakerは提案者を取り違えている。', 'The minutes fix the venue and leave the caterer open; the conversation reverses this: the venue changes due to renovation while the caterer is settled, and only combining both sources gives the true outcome.', '[{"term": "仕出し業者", "reading": "しだしぎょうしゃ", "meaning": "catering vendor"}, {"term": "押さえる", "reading": "おさえる", "meaning": "to reserve/secure (a venue)"}]', '[{"template": "meeting_minutes", "title": "新製品発表会 会場・準備 打ち合わせ 議事録", "meta": [{"label": "日時", "value": "9月5日（木）10時〜11時"}, {"label": "場所", "value": "第二会議室"}, {"label": "出席者", "value": "同僚A、同僚B、山田"}], "blocks": [{"type": "numbered", "items": ["会場はAホールに決定。", "予算は50万円以内とする。", "仕出し業者は未定。次回までに検討する。"]}]}]', '[{"speaker_role": "同僚A", "text": "議事録では会場はAホールに決まっていましたが、先週連絡があって、Aホールは改装工事で使えなくなったそうです。", "clip_id": "ca8e43d4b5d3cad6"}, {"speaker_role": "同僚B", "text": "それは困りますね。代わりの案はあるんですか。", "clip_id": "260597879e7e88df"}, {"speaker_role": "同僚A", "text": "Bホールを押さえました。広さも予算内に収まります。", "clip_id": "0bf957ed219656f3"}, {"speaker_role": "同僚B", "text": "分かりました。仕出し業者はどうなりましたか。議事録では未定のままでしたが。", "clip_id": "28346885e5f18f68"}, {"speaker_role": "同僚A", "text": "それは山田さんがX社に決めたと聞いています。", "clip_id": "fd85153bd6e5a2f1"}, {"speaker_role": "同僚B", "text": "では、会場と仕出し、両方とも決まったということですね。", "clip_id": "11e96cb2010d343e"}]', '89720e51a9160978', 1.0) on conflict (id) do update set bundle_id = excluded.bundle_id, item_type = excluded.item_type, level = excluded.level, seed_cell_id = excluded.seed_cell_id, setting = excluded.setting, relation = excluded.relation, function = excluded.function, channel = excluded.channel, scene_id = excluded.scene_id, speaker_role = excluded.speaker_role, listener_role = excluded.listener_role, topic = excluded.topic, stem = excluded.stem, correct_index = excluded.correct_index, explanation_ja = excluded.explanation_ja, explanation_en = excluded.explanation_en, vocab_notes = excluded.vocab_notes, documents = excluded.documents, dialogue = excluded.dialogue, narration_clip_id = excluded.narration_clip_id, model_p_correct = excluded.model_p_correct;
insert into items (id, bundle_id, item_type, level, seed_cell_id, setting, relation, function, channel, scene_id, speaker_role, listener_role, topic, stem, correct_index, explanation_ja, explanation_en, vocab_notes, documents, dialogue, narration_clip_id, model_p_correct) values ('dc756cc425', 'sougou_choudokkai_J1_002', 'sougou_choudokkai', 'J1', 'video_review+superior_to_subordinate+reconcile_document@J1', 'video_review', 'superior_to_subordinate', 'reconcile_document', 'video', 'scene_video_call_laptop', null, null, '新人研修の会場担当の引き継ぎ', '研修当日の会場対応は、誰が行うことになりましたか。', 2, '議事録では会場の予約・当日対応・昼食の手配がすべて中村の担当とされているが、会話で中村が研修当日は出張で不在になることが分かり、部長が当日対応だけを佐藤に依頼している。昼食の手配は出張前に中村が済ませる予定なので変更されていない。議事録だけでは出張の事実が分からず、会話だけでは元の担当割り振りが分からないため、両方を照合しないと正解できない。', 'The minutes assign everything to Nakamura, but the call reveals Nakamura will be away, so the manager moves only the on-site duty to Sato, leaving the lunch arrangement unchanged.', '[{"term": "引き継ぐ", "reading": "ひきつぐ", "meaning": "to take over / hand over (a task)"}, {"term": "手配", "reading": "てはい", "meaning": "arrangement, making arrangements"}]', '[{"template": "meeting_minutes", "title": "新人研修 運営打ち合わせ 議事録", "meta": [{"label": "日時", "value": "9月5日 15時"}, {"label": "場所", "value": "オンライン"}, {"label": "出席者", "value": "部長、中村、佐藤"}], "blocks": [{"type": "table", "columns": ["項目", "担当"], "rows": [["会場の予約", "中村"], ["当日対応", "中村"], ["昼食の手配", "中村"]]}, {"type": "bullets", "items": ["研修は9月20日実施。", "詳細は担当者が各自進めること。"]}]}]', '[{"speaker_role": "部長", "text": "議事録では、会場の予約と当日対応、それに昼食の手配まで、すべて中村さんになっていますね。", "clip_id": "6c56f26bb38d3038"}, {"speaker_role": "部下", "text": "はい。ただ、中村さんは来週から出張で、研修当日は不在の予定です。", "clip_id": "d64533cf7fe8ccc5"}, {"speaker_role": "部長", "text": "それは困りますね。予約はもう済んでいるようですが、当日対応は佐藤さんにお願いできますか。", "clip_id": "e357a5e2ef1b42db"}, {"speaker_role": "部下", "text": "承知しました。私が当日対応いたします。", "clip_id": "ef6bf54f12483df1"}, {"speaker_role": "部下", "text": "昼食の手配については、中村さんが出張前に済ませると言っていました。", "clip_id": "6b2ab03f77832a05"}, {"speaker_role": "部長", "text": "それはそのままで結構です。", "clip_id": "e33a1f16704f607c"}]', 'a4e7430667229af8', 1.0) on conflict (id) do update set bundle_id = excluded.bundle_id, item_type = excluded.item_type, level = excluded.level, seed_cell_id = excluded.seed_cell_id, setting = excluded.setting, relation = excluded.relation, function = excluded.function, channel = excluded.channel, scene_id = excluded.scene_id, speaker_role = excluded.speaker_role, listener_role = excluded.listener_role, topic = excluded.topic, stem = excluded.stem, correct_index = excluded.correct_index, explanation_ja = excluded.explanation_ja, explanation_en = excluded.explanation_en, vocab_notes = excluded.vocab_notes, documents = excluded.documents, dialogue = excluded.dialogue, narration_clip_id = excluded.narration_clip_id, model_p_correct = excluded.model_p_correct;

-- Options are replaced wholesale rather than upserted: a corrected item can
-- have fewer options or a different order, and a stale row left behind would
-- be a fifth answer nobody meant to publish.
delete from item_options where item_id in ('23fd538a62', '2bb7e73bae', 'dc756cc425');
insert into item_options (item_id, position, text, role, why, clip_id) values ('23fd538a62', 0, '9月15日から', 'stated_by_wrong_speaker', '経理部担当者がそう確認しているが、それはテスト環境構築の予定日であり、システム部担当者がその場で訂正している。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('23fd538a62', 1, '10月8日から', 'correct', 'システム部担当者が、ベンダー側の人員不足でデータ移行の開始自体が1週間遅れ、10月8日からになったと明言している。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('23fd538a62', 2, '10月1日から', 'combines_wrong_pair', '報告書に書かれた当初の予定日のままで、会話で述べられたベンダー都合の1週間遅れを反映していない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('23fd538a62', 3, '10月15日から', 'unsupported_but_plausible', 'さらなる遅れとしてありそうな日付だが、会話にも報告書にも述べられていない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('2bb7e73bae', 0, '会場は同僚Bの提案でBホールに変更され、仕出し業者はX社に決定した。', 'stated_by_wrong_speaker', 'Bホールを押さえて報告したのは同僚Aであり、同僚Bが提案したという事実はない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('2bb7e73bae', 1, '会場はBホールに変更され、仕出し業者は同僚Bが決定した。', 'wrong_action_owner', '仕出し業者をX社に決めたのは山田であり、同僚Bではない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('2bb7e73bae', 2, '会場はBホールに変更され、仕出し業者はX社に決定した。', 'correct', 'Aホールが使えなくなったためBホールに変更され、未定だった仕出し業者は山田がX社に決めたと会話で述べられている。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('2bb7e73bae', 3, '会場はAホールのままで、仕出し業者はX社に決定した。', 'combines_wrong_pair', '仕出し業者の決定は会話の内容だが、会場は議事録どおりAホールのままとしており、変更の事実が反映されていない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('dc756cc425', 0, '中村が行う。', 'combines_wrong_pair', '議事録の担当者欄のままで、中村が出張で不在になるという会話の内容を反映していない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('dc756cc425', 1, '中村が出張を短縮して対応する。', 'unsupported_but_plausible', '出張を切り上げて戻る可能性はあり得るが、会話ではそのような話は一切出ていない。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('dc756cc425', 2, '佐藤が行う。', 'correct', '中村が出張で当日不在になるため、部長が佐藤に当日対応を依頼し、佐藤も了承している。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('dc756cc425', 3, '佐藤が昼食の手配も合わせて行う。', 'wrong_action_owner', '昼食の手配は中村が出張前に済ませると述べており、佐藤が引き継いだのは会場対応だけである。', null) on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;

-- Withdrawn after review: batches/withdrawn.txt says why. An unpublish,
-- never a delete, so every answer already given keeps resolving. Nothing
-- here ever sets is_published back to 1: a question the owner vetoed
-- in the app stays vetoed however often this file is applied.
update items set is_published = 0
 where id in ('23fd538a62');

