-- sougou_choukai_J1_003: 1 × sougou_choukai (J1)
-- generated 2026-10-05T22:44:45+00:00 by claude-sonnet-5
-- Produced by bjt publish. Idempotent: re-running replaces these rows.

-- Scenes are a shared bank (or, for 画像把握, one picture per item),
-- image_path stays null until the art exists, and is deliberately not
-- overwritten by a re-publish.
insert into scenes (id, label_ja) values ('scene_phone_desk', 'デスクで固定電話') on conflict (id) do update set label_ja = excluded.label_ja;

-- One row per distinct utterance. audio_path is filled in by the TTS step.
insert into audio_clips (id, text, voice, channel) values ('9327c4850de72c57', '前回の役員体制案から、何が変わりましたか。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('435280fa25813318', 'お疲れさまです。前回ご説明した役員体制案について、変更がありましたのでご報告します。', 'manager_m', 'phone') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('bd564e8efb2cdb8a', 'お願いします。前回は社外から監査役を一名招聘し、取締役は八名を維持するという内容でしたね。', 'staff_junior_m', 'phone') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('eb9927bd090e87e2', 'はい、そうでした。昨日の経営会議で、取締役を八名から五名に減らす案が出たのですが、株主からの反発が予想されるとのことで、結局六名に落ち着きました。', 'manager_m', 'phone') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('7ae6f7abb68a30f6', '監査役のほうは、社外招聘のままですか。', 'staff_junior_m', 'phone') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('1e2b07f55179fe8b', 'いえ、そちらも変わりまして、社外から新たに迎えるのではなく、現在の顧問弁護士に監査役を兼任していただくことになりました。', 'manager_m', 'phone') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('cdeeedc7f89211d7', 'なるほど、人件費を抑える狙いですね。株主総会での承認はこれからですか。', 'staff_junior_m', 'phone') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('267d733f7763bdf4', 'はい、来月の総会にかけることになります。', 'manager_m', 'phone') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('25c7c1a4fbc76235', 'いち', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('b360b9e9cfaf82e5', '取締役は六名に減り、監査役は新たに迎えず顧問弁護士が兼任することになった。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('6e34bf5479a4824e', 'に', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('6f2b59a728411e18', '取締役を八名から五名に減らすことになった。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('a94822f17a881031', 'さん', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('8de877effd2c3b5b', '新しい監査役として社外から弁護士を招聘することになった。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('5577d7cacee29a6c', 'よん', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('d64bf718bf9a04c2', '先輩が、監査役を顧問弁護士に兼任させる案を提案した。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;

insert into bundles (id, item_type, level, generator_model, generated_at) values ('sougou_choukai_J1_003', 'sougou_choukai', 'J1', 'claude-sonnet-5', '2026-10-05T22:44:45+00:00') on conflict (id) do update set item_type = excluded.item_type, level = excluded.level, generator_model = excluded.generator_model, generated_at = excluded.generated_at;

insert into items (id, bundle_id, item_type, level, seed_cell_id, setting, relation, function, channel, scene_id, speaker_role, listener_role, topic, stem, correct_index, explanation_ja, explanation_en, vocab_notes, documents, dialogue, narration_clip_id, model_p_correct) values ('dd945a7ce3', 'sougou_choukai_J1_003', 'sougou_choukai', 'J1', 'conference_call+junior_to_senior+what_changed@J1', 'conference_call', 'junior_to_senior', 'what_changed', 'phone', 'scene_phone_desk', null, null, '役員体制案の変更点', '前回の役員体制案から、何が変わりましたか。', 0, '前回案は監査役を社外から一名招聘し取締役は八名を維持する内容だった。最終的には、取締役は五名案が一度検討されたものの株主の反発を懸念して六名に落ち着き、監査役は社外から新たに迎えるのではなく現職の顧問弁護士が兼任する形に変わった。五名案は途中で修正されており、兼任案は後輩が報告した内容であって先輩が提案したものではない。弁護士という語を使った選択肢も、実際には新規招聘ではなく既存顧問の兼任であり、事実と異なる。', 'The final plan settles on six directors (not five, which was floated and revised) and has the existing legal advisor take on the auditor role rather than hiring a new outside auditor; the proposal came from the junior''s report, not the senior''s suggestion.', '[{"term": "監査役", "reading": "かんさやく", "meaning": "company auditor (board-level oversight role)"}, {"term": "取締役", "reading": "とりしまりやく", "meaning": "director (board member)"}, {"term": "兼任", "reading": "けんにん", "meaning": "to hold a post concurrently"}, {"term": "招聘", "reading": "しょうへい", "meaning": "to invite/recruit (a person to a position)"}]', '[]', '[{"speaker_role": "後輩", "text": "お疲れさまです。前回ご説明した役員体制案について、変更がありましたのでご報告します。", "clip_id": "435280fa25813318"}, {"speaker_role": "先輩", "text": "お願いします。前回は社外から監査役を一名招聘し、取締役は八名を維持するという内容でしたね。", "clip_id": "bd564e8efb2cdb8a"}, {"speaker_role": "後輩", "text": "はい、そうでした。昨日の経営会議で、取締役を八名から五名に減らす案が出たのですが、株主からの反発が予想されるとのことで、結局六名に落ち着きました。", "clip_id": "eb9927bd090e87e2"}, {"speaker_role": "先輩", "text": "監査役のほうは、社外招聘のままですか。", "clip_id": "7ae6f7abb68a30f6"}, {"speaker_role": "後輩", "text": "いえ、そちらも変わりまして、社外から新たに迎えるのではなく、現在の顧問弁護士に監査役を兼任していただくことになりました。", "clip_id": "1e2b07f55179fe8b"}, {"speaker_role": "先輩", "text": "なるほど、人件費を抑える狙いですね。株主総会での承認はこれからですか。", "clip_id": "cdeeedc7f89211d7"}, {"speaker_role": "後輩", "text": "はい、来月の総会にかけることになります。", "clip_id": "267d733f7763bdf4"}]', '9327c4850de72c57', 1.0) on conflict (id) do update set bundle_id = excluded.bundle_id, item_type = excluded.item_type, level = excluded.level, seed_cell_id = excluded.seed_cell_id, setting = excluded.setting, relation = excluded.relation, function = excluded.function, channel = excluded.channel, scene_id = excluded.scene_id, speaker_role = excluded.speaker_role, listener_role = excluded.listener_role, topic = excluded.topic, stem = excluded.stem, correct_index = excluded.correct_index, explanation_ja = excluded.explanation_ja, explanation_en = excluded.explanation_en, vocab_notes = excluded.vocab_notes, documents = excluded.documents, dialogue = excluded.dialogue, narration_clip_id = excluded.narration_clip_id, model_p_correct = excluded.model_p_correct;

-- Options are replaced wholesale rather than upserted: a corrected item can
-- have fewer options or a different order, and a stale row left behind would
-- be a fifth answer nobody meant to publish.
delete from item_options where item_id in ('dd945a7ce3');
insert into item_options (item_id, position, text, role, why, clip_id) values ('dd945a7ce3', 0, '取締役は六名に減り、監査役は新たに迎えず顧問弁護士が兼任することになった。', 'correct', '後輩が経営会議の結果として報告した最終案で、取締役は六名、監査役は社外招聘をやめて現職の顧問弁護士が兼任すると述べている。', 'b360b9e9cfaf82e5') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('dd945a7ce3', 1, '取締役を八名から五名に減らすことになった。', 'superseded_by_later_turn', '五名案は経営会議で一度出たものの、株主の反発が予想されるとして六名に修正されており、最終案ではない。', '6f2b59a728411e18') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('dd945a7ce3', 2, '新しい監査役として社外から弁護士を招聘することになった。', 'surface_keyword_match', '弁護士という語は出てくるが、実際は社外から新たに招くのではなく、既存の顧問弁護士が監査役を兼任する話である。', '8de877effd2c3b5b') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('dd945a7ce3', 3, '先輩が、監査役を顧問弁護士に兼任させる案を提案した。', 'stated_by_wrong_speaker', '兼任案を報告したのは後輩で、先輩は報告を聞いて人件費削減の狙いだと感想を述べただけである。', 'd64bf718bf9a04c2') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;

