-- sougou_choukai_J1_002: 1 × sougou_choukai (J1)
-- generated 2026-10-02T21:45:20+00:00 by claude-sonnet-5
-- Produced by bjt publish. Idempotent: re-running replaces these rows.

-- Scenes are a shared bank (or, for 画像把握, one picture per item),
-- image_path stays null until the art exists, and is deliberately not
-- overwritten by a re-publish.
insert into scenes (id, label_ja) values ('scene_office_desk_pair', '自分の席で向かい合う二人') on conflict (id) do update set label_ja = excluded.label_ja;

-- One row per distinct utterance. audio_path is filled in by the TTS step.
insert into audio_clips (id, text, voice, channel) values ('0fa4140a0b6ae8a0', '山川商事への対応について、結論はどうなりましたか。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('0fea7fe676806729', '先輩、山川商事から見積もりの件で連絡がありまして、値引きと納期短縮の両方を求められています。', 'manager_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('592d77a770a45b0f', 'どのくらい求められているの。', 'staff_junior_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('fb6ae93c7ad8eec2', '値引きは一割、納期も一週間早めてほしいとのことです。私としては、一割は飲んで関係を強化したほうがいいと思うのですが。', 'manager_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('e130bff5be205da8', '一割はさすがに厳しいよ。五％なら原価的に飲める。納期短縮は生産ラインに空きがあるから対応できそうだし、両方いけるんじゃないか。', 'staff_junior_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('3acce30aadb219b9', 'では五％の値引きと納期一週間短縮、両方を提案書に盛り込みますか。', 'manager_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('ae90aaf7526953db', 'いや、待って。さっき空きがあると言ったけど、来月分の受注が入ったから、納期短縮まではもう無理だ。値引きを五％にするなら、納期は今まで通りでいこう。', 'staff_junior_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('5260cabbcdc46067', '承知しました。値引き五％、納期は従来どおりという形で先方にお伝えします。', 'manager_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('25c7c1a4fbc76235', 'いち', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('bcdac78baa90ccf2', '値引き五％にして、納期も一週間短縮する。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('6e34bf5479a4824e', 'に', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('548682030c361d9e', '後輩の意見どおり、一割の値引きを行う。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('a94822f17a881031', 'さん', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('d7b87f2af20b51ce', '値引きは五％にとどめ、納期は従来どおりとする。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('5577d7cacee29a6c', 'よん', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('f7b3d9ec71ea7413', '値引きはせず、納期だけ一週間短縮する。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;

insert into bundles (id, item_type, level, generator_model, generated_at) values ('sougou_choukai_J1_002', 'sougou_choukai', 'J1', 'claude-sonnet-5', '2026-10-02T21:45:20+00:00') on conflict (id) do update set item_type = excluded.item_type, level = excluded.level, generator_model = excluded.generator_model, generated_at = excluded.generated_at;

insert into items (id, bundle_id, item_type, level, seed_cell_id, setting, relation, function, channel, scene_id, speaker_role, listener_role, topic, stem, correct_index, explanation_ja, explanation_en, vocab_notes, documents, dialogue, narration_clip_id, model_p_correct) values ('641b8c655c', 'sougou_choukai_J1_002', 'sougou_choukai', 'J1', 'desk_huddle+junior_to_senior+what_was_decided@J1', 'desk_huddle', 'junior_to_senior', 'what_was_decided', 'in_person', 'scene_office_desk_pair', null, null, '取引先への値引き・納期対応の結論', '山川商事への対応について、結論はどうなりましたか。', 2, '後輩は最初、取引先の求め通り一割の値引きを飲むべきだと述べるが、先輩は「一割はさすがに厳しい」と否定し、五％なら対応できると言う。さらに先輩はいったん「納期短縮も含めて両方いけるんじゃないか」と述べるが、来月分の受注が入ったことに気づき、納期短縮は無理だと撤回する。最終的な結論は、値引きを五％にとどめ、納期は従来どおりとすることで、後輩もそのように先方へ伝えると答えている。途中で出た「一割」や「両方いける」という発言をそのまま答えにすると誤りになる。', 'The junior''s suggestion of a 10% discount is rejected, and the senior''s early idea of doing both a discount and a shorter delivery is withdrawn once a conflicting order comes in; the final decision is a 5% discount with the delivery date unchanged.', '[{"term": "納期", "reading": "のうき", "meaning": "delivery date/deadline"}, {"term": "受注", "reading": "じゅちゅう", "meaning": "receiving an order"}, {"term": "原価", "reading": "げんか", "meaning": "cost price"}]', '[]', '[{"speaker_role": "後輩", "text": "先輩、山川商事から見積もりの件で連絡がありまして、値引きと納期短縮の両方を求められています。", "clip_id": "0fea7fe676806729"}, {"speaker_role": "先輩", "text": "どのくらい求められているの。", "clip_id": "592d77a770a45b0f"}, {"speaker_role": "後輩", "text": "値引きは一割、納期も一週間早めてほしいとのことです。私としては、一割は飲んで関係を強化したほうがいいと思うのですが。", "clip_id": "fb6ae93c7ad8eec2"}, {"speaker_role": "先輩", "text": "一割はさすがに厳しいよ。五％なら原価的に飲める。納期短縮は生産ラインに空きがあるから対応できそうだし、両方いけるんじゃないか。", "clip_id": "e130bff5be205da8"}, {"speaker_role": "後輩", "text": "では五％の値引きと納期一週間短縮、両方を提案書に盛り込みますか。", "clip_id": "3acce30aadb219b9"}, {"speaker_role": "先輩", "text": "いや、待って。さっき空きがあると言ったけど、来月分の受注が入ったから、納期短縮まではもう無理だ。値引きを五％にするなら、納期は今まで通りでいこう。", "clip_id": "ae90aaf7526953db"}, {"speaker_role": "後輩", "text": "承知しました。値引き五％、納期は従来どおりという形で先方にお伝えします。", "clip_id": "5260cabbcdc46067"}]', '0fa4140a0b6ae8a0', 1.0) on conflict (id) do update set bundle_id = excluded.bundle_id, item_type = excluded.item_type, level = excluded.level, seed_cell_id = excluded.seed_cell_id, setting = excluded.setting, relation = excluded.relation, function = excluded.function, channel = excluded.channel, scene_id = excluded.scene_id, speaker_role = excluded.speaker_role, listener_role = excluded.listener_role, topic = excluded.topic, stem = excluded.stem, correct_index = excluded.correct_index, explanation_ja = excluded.explanation_ja, explanation_en = excluded.explanation_en, vocab_notes = excluded.vocab_notes, documents = excluded.documents, dialogue = excluded.dialogue, narration_clip_id = excluded.narration_clip_id, model_p_correct = excluded.model_p_correct;

-- Options are replaced wholesale rather than upserted: a corrected item can
-- have fewer options or a different order, and a stale row left behind would
-- be a fifth answer nobody meant to publish.
delete from item_options where item_id in ('641b8c655c');
insert into item_options (item_id, position, text, role, why, clip_id) values ('641b8c655c', 0, '値引き五％にして、納期も一週間短縮する。', 'superseded_by_later_turn', '先輩が一度は「両方いけるんじゃないか」と述べたが、来月分の受注が入ったことを理由に直後で撤回している。', 'bcdac78baa90ccf2') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('641b8c655c', 1, '後輩の意見どおり、一割の値引きを行う。', 'stated_by_wrong_speaker', '一割の値引きを提案したのは後輩自身であり、先輩は「一割はさすがに厳しいよ」と明確に否定している。', '548682030c361d9e') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('641b8c655c', 2, '値引きは五％にとどめ、納期は従来どおりとする。', 'correct', '先輩が「値引きを五％にするなら、納期は今まで通りでいこう」と最後に決め、後輩もその形で先方に伝えると応じている。', 'd7b87f2af20b51ce') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('641b8c655c', 3, '値引きはせず、納期だけ一週間短縮する。', 'unsupported_but_plausible', '現場の空き状況から考えればありえそうな対応だが、会話ではそのような組み合わせは一度も話し合われていない。', 'f7b3d9ec71ea7413') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;

-- Withdrawn after review: batches/withdrawn.txt says why. An unpublish,
-- never a delete, so every answer already given keeps resolving. Nothing
-- here ever sets is_published back to 1: a question the owner vetoed
-- in the app stays vetoed however often this file is applied.
update items set is_published = 0
 where id in ('641b8c655c');

