-- sougou_choukai_J3_002: 1 × sougou_choukai (J3)
-- generated 2026-10-04T19:41:27+00:00 by claude-sonnet-5
-- Produced by bjt publish. Idempotent: re-running replaces these rows.

-- Scenes are a shared bank (or, for 画像把握, one picture per item),
-- image_path stays null until the art exists, and is deliberately not
-- overwritten by a re-publish.
insert into scenes (id, label_ja) values ('scene_video_call_laptop', 'ノートPCでオンライン会議') on conflict (id) do update set label_ja = excluded.label_ja;

-- One row per distinct utterance. audio_path is filled in by the TTS step.
insert into audio_clips (id, text, voice, channel) values ('e8ad7a499764a247', 'この後、後輩はまず何をすることになりましたか。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('075598dea3e2a2c7', 'お疲れさまです。明日の提案資料、ご確認いただけましたか。', 'manager_m', 'video') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('b708f38b3346076f', '見ました。数字のところ、先月の人数で止まっていますね。', 'staff_junior_m', 'video') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('04ca6c6afa50edfd', 'あ、すみません。今月分に差し替えて先方に送ります。', 'manager_m', 'video') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('9da23b40917a6855', 'いえ、待ってください。今月の数字はまだ最終確定していなくて、課長が今週中に見直すと言っていました。', 'staff_junior_m', 'video') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('817f8b43fa6c05b6', 'では、数字はそのままで送ってしまってよろしいでしょうか。', 'manager_m', 'video') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('8e5c57edecb939c9', 'いや、数字が変わる可能性があるので、送るのは待ちましょう。先に課長に確認してから、私から先方に連絡します。', 'staff_junior_m', 'video') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('f0ed79bb8590a7dd', '承知しました。では私は表紙のロゴだけ新しいものに差し替えておきます。', 'manager_m', 'video') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('3e46c9b64ba89535', 'お願いします。', 'staff_junior_m', 'video') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('25c7c1a4fbc76235', 'いち', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('4e653d4e910d41db', '先方に電話して資料の送付が遅れる旨を伝える', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('6e34bf5479a4824e', 'に', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('e365d9a573a15515', '今月分の数字に差し替えて先方に送る', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('a94822f17a881031', 'さん', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('8caec5cb1295591e', '資料の表紙のロゴを新しいものに差し替える', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('5577d7cacee29a6c', 'よん', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('c966576d70ecb1d9', '課長に今月の数字の確認を取る', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;

insert into bundles (id, item_type, level, generator_model, generated_at) values ('sougou_choukai_J3_002', 'sougou_choukai', 'J3', 'claude-sonnet-5', '2026-10-04T19:41:27+00:00') on conflict (id) do update set item_type = excluded.item_type, level = excluded.level, generator_model = excluded.generator_model, generated_at = excluded.generated_at;

insert into items (id, bundle_id, item_type, level, seed_cell_id, setting, relation, function, channel, scene_id, speaker_role, listener_role, topic, stem, correct_index, explanation_ja, explanation_en, vocab_notes, documents, dialogue, narration_clip_id, model_p_correct) values ('476ba519b9', 'sougou_choukai_J3_002', 'sougou_choukai', 'J3', 'video_meeting+junior_to_senior+next_step@J3', 'video_meeting', 'junior_to_senior', 'next_step', 'video', 'scene_video_call_laptop', null, null, '提案資料の送付前の対応分担', 'この後、後輩はまず何をすることになりましたか。', 2, '後輩は当初、今月分の数字に直してすぐ先方へ送るつもりだったが、先輩が「課長がまだ見直すと言っていた」として送付を止め、確認が済むまで自分が対応すると述べた。後輩はその間の作業として表紙のロゴの差し替えを申し出ており、これが次に行うことになる。数字の確認は先輩の担当であり、先方への連絡や電話の話は会話に出ていない。', 'The junior''s original plan to update the numbers and send is overridden mid-conversation; the senior will confirm the figures, and the junior''s actual next task is replacing the logo.', '[{"term": "差し替える", "reading": "さしかえる", "meaning": "to replace/swap out"}, {"term": "最終確定", "reading": "さいしゅうかくてい", "meaning": "final confirmation"}]', '[]', '[{"speaker_role": "後輩", "text": "お疲れさまです。明日の提案資料、ご確認いただけましたか。", "clip_id": "075598dea3e2a2c7"}, {"speaker_role": "先輩", "text": "見ました。数字のところ、先月の人数で止まっていますね。", "clip_id": "b708f38b3346076f"}, {"speaker_role": "後輩", "text": "あ、すみません。今月分に差し替えて先方に送ります。", "clip_id": "04ca6c6afa50edfd"}, {"speaker_role": "先輩", "text": "いえ、待ってください。今月の数字はまだ最終確定していなくて、課長が今週中に見直すと言っていました。", "clip_id": "9da23b40917a6855"}, {"speaker_role": "後輩", "text": "では、数字はそのままで送ってしまってよろしいでしょうか。", "clip_id": "817f8b43fa6c05b6"}, {"speaker_role": "先輩", "text": "いや、数字が変わる可能性があるので、送るのは待ちましょう。先に課長に確認してから、私から先方に連絡します。", "clip_id": "8e5c57edecb939c9"}, {"speaker_role": "後輩", "text": "承知しました。では私は表紙のロゴだけ新しいものに差し替えておきます。", "clip_id": "f0ed79bb8590a7dd"}, {"speaker_role": "先輩", "text": "お願いします。", "clip_id": "3e46c9b64ba89535"}]', 'e8ad7a499764a247', 1.0) on conflict (id) do update set bundle_id = excluded.bundle_id, item_type = excluded.item_type, level = excluded.level, seed_cell_id = excluded.seed_cell_id, setting = excluded.setting, relation = excluded.relation, function = excluded.function, channel = excluded.channel, scene_id = excluded.scene_id, speaker_role = excluded.speaker_role, listener_role = excluded.listener_role, topic = excluded.topic, stem = excluded.stem, correct_index = excluded.correct_index, explanation_ja = excluded.explanation_ja, explanation_en = excluded.explanation_en, vocab_notes = excluded.vocab_notes, documents = excluded.documents, dialogue = excluded.dialogue, narration_clip_id = excluded.narration_clip_id, model_p_correct = excluded.model_p_correct;

-- Options are replaced wholesale rather than upserted: a corrected item can
-- have fewer options or a different order, and a stale row left behind would
-- be a fifth answer nobody meant to publish.
delete from item_options where item_id in ('476ba519b9');
insert into item_options (item_id, position, text, role, why, clip_id) values ('476ba519b9', 0, '先方に電話して資料の送付が遅れる旨を伝える', 'unsupported_but_plausible', 'ありそうな対応だが、会話では誰もその連絡をするとは言っていない。', '4e653d4e910d41db') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('476ba519b9', 1, '今月分の数字に差し替えて先方に送る', 'superseded_by_later_turn', '後輩が最初にそのつもりを述べたが、数字がまだ確定していないとして先輩に止められている。', 'e365d9a573a15515') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('476ba519b9', 2, '資料の表紙のロゴを新しいものに差し替える', 'correct', '先輩が数字の確認を終えるまで送付を保留すると決めたあと、後輩が自分の作業として申し出て先輩も了承している。', '8caec5cb1295591e') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('476ba519b9', 3, '課長に今月の数字の確認を取る', 'stated_by_wrong_speaker', '数字を確認するのは先輩が自分で行うと述べており、後輩の作業ではない。', 'c966576d70ecb1d9') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;

