-- sougou_choukai_J3_003: 1 × sougou_choukai (J3)
-- generated 2026-10-07T21:25:30+00:00 by claude-sonnet-5
-- Produced by bjt publish. Idempotent: re-running replaces these rows.

-- Scenes are a shared bank (or, for 画像把握, one picture per item),
-- image_path stays null until the art exists, and is deliberately not
-- overwritten by a re-publish.
insert into scenes (id, label_ja) values ('scene_meeting_room_table', '社内の会議室のテーブル') on conflict (id) do update set label_ja = excluded.label_ja;

-- One row per distinct utterance. audio_path is filled in by the TTS step.
insert into audio_clips (id, text, voice, channel) values ('8bbcc26ca55109b1', 'みどり物産との交渉について、前回の合意内容から何が変わりましたか。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('8ef8a80a9858403d', 'みどり物産との件、前回は単価を3％引き下げて、納期も4週間から2週間に短縮するという話でしたよね。今回もその通りで決まったんですか。', 'manager_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('2f009b15d794eeae', 'それが、先方の事情で単価の引き下げは今回見送りになりまして。', 'staff_junior_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('e3e24903830f0369', 'いえ、単価は引き続き3％下げる方向だと聞いていますけど。', 'staff_mid_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('e91cdaf36c561dc5', 'いや、さっき先方から連絡がありまして、材料費が上がっているとのことで、引き下げはなしになりました。ただ、納期短縮の2週間のほうは、そのまま進めることで合意しています。', 'staff_junior_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('a3daf37e24d2a808', '分かりました。では製造スケジュールは2週間に合わせて組みますね。', 'manager_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('884de14daa505eb7', 'お願いします。', 'staff_junior_m', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('25c7c1a4fbc76235', 'いち', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('203ae82b2c260969', '納期は4週間のまま変わらず、単価だけ3％引き下げられた。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('6e34bf5479a4824e', 'に', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('a73f9251c8839672', '単価を3％引き下げ、納期も2週間に短縮することで合意した。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('a94822f17a881031', 'さん', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('3e8d4820c6eb17b7', '単価は予定通り3％引き下げられ、納期は4週間のままとなった。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('5577d7cacee29a6c', 'よん', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;
insert into audio_clips (id, text, voice, channel) values ('3954a5b9d72a7adb', '単価の引き下げは見送られたが、納期短縮の2週間は維持された。', 'narrator_f', 'in_person') on conflict (id) do update set text = excluded.text, voice = excluded.voice, channel = excluded.channel;

insert into bundles (id, item_type, level, generator_model, generated_at) values ('sougou_choukai_J3_003', 'sougou_choukai', 'J3', 'claude-sonnet-5', '2026-10-07T21:25:30+00:00') on conflict (id) do update set item_type = excluded.item_type, level = excluded.level, generator_model = excluded.generator_model, generated_at = excluded.generated_at;

insert into items (id, bundle_id, item_type, level, seed_cell_id, setting, relation, function, channel, scene_id, speaker_role, listener_role, topic, stem, correct_index, explanation_ja, explanation_en, vocab_notes, documents, dialogue, narration_clip_id, model_p_correct) values ('e30344079e', 'sougou_choukai_J3_003', 'sougou_choukai', 'J3', 'negotiation+other_department+what_changed@J3', 'negotiation', 'other_department', 'what_changed', 'in_person', 'scene_meeting_room_table', null, null, '交渉条件の一部変更報告', 'みどり物産との交渉について、前回の合意内容から何が変わりましたか。', 3, '前回は「単価3％引き下げ、納期2週間短縮」で合意していたが、今回は材料費の高騰により単価引き下げが見送りになった。一方、納期短縮の2週間については先方にとっても重要なためそのまま維持されることになった。営業部の担当者Bが「単価は引き続き下がる」と発言するが、これはAに訂正されており誤り。また4週間や3％という数字は前回や交渉前の条件であり、今回の結論をそのまま表すものではない。会話の流れを追わないと、前回の合意内容や途中の誤った発言をそのまま答えに選んでしまう。', 'The price cut is dropped due to rising material costs, but the two-week delivery shortening stays; a colleague''s incorrect guess and earlier figures are traps.', '[{"term": "単価", "reading": "たんか", "meaning": "unit price"}, {"term": "見送る", "reading": "みおくる", "meaning": "to postpone or forgo"}, {"term": "納期短縮", "reading": "のうきたんしゅく", "meaning": "shortening of the delivery deadline"}]', '[]', '[{"speaker_role": "製造部の担当者", "text": "みどり物産との件、前回は単価を3％引き下げて、納期も4週間から2週間に短縮するという話でしたよね。今回もその通りで決まったんですか。", "clip_id": "8ef8a80a9858403d"}, {"speaker_role": "営業部の担当者A", "text": "それが、先方の事情で単価の引き下げは今回見送りになりまして。", "clip_id": "2f009b15d794eeae"}, {"speaker_role": "営業部の担当者B", "text": "いえ、単価は引き続き3％下げる方向だと聞いていますけど。", "clip_id": "e3e24903830f0369"}, {"speaker_role": "営業部の担当者A", "text": "いや、さっき先方から連絡がありまして、材料費が上がっているとのことで、引き下げはなしになりました。ただ、納期短縮の2週間のほうは、そのまま進めることで合意しています。", "clip_id": "e91cdaf36c561dc5"}, {"speaker_role": "製造部の担当者", "text": "分かりました。では製造スケジュールは2週間に合わせて組みますね。", "clip_id": "a3daf37e24d2a808"}, {"speaker_role": "営業部の担当者A", "text": "お願いします。", "clip_id": "884de14daa505eb7"}]', '8bbcc26ca55109b1', 1.0) on conflict (id) do update set bundle_id = excluded.bundle_id, item_type = excluded.item_type, level = excluded.level, seed_cell_id = excluded.seed_cell_id, setting = excluded.setting, relation = excluded.relation, function = excluded.function, channel = excluded.channel, scene_id = excluded.scene_id, speaker_role = excluded.speaker_role, listener_role = excluded.listener_role, topic = excluded.topic, stem = excluded.stem, correct_index = excluded.correct_index, explanation_ja = excluded.explanation_ja, explanation_en = excluded.explanation_en, vocab_notes = excluded.vocab_notes, documents = excluded.documents, dialogue = excluded.dialogue, narration_clip_id = excluded.narration_clip_id, model_p_correct = excluded.model_p_correct;

-- Options are replaced wholesale rather than upserted: a corrected item can
-- have fewer options or a different order, and a stale row left behind would
-- be a fifth answer nobody meant to publish.
delete from item_options where item_id in ('e30344079e');
insert into item_options (item_id, position, text, role, why, clip_id) values ('e30344079e', 0, '納期は4週間のまま変わらず、単価だけ3％引き下げられた。', 'surface_keyword_match', '4週間と3％という数字は会話に出てくるが、どちらも前回や交渉前の数値で、今回の結論とは逆の組み合わせになっている。', '203ae82b2c260969') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('e30344079e', 1, '単価を3％引き下げ、納期も2週間に短縮することで合意した。', 'superseded_by_later_turn', 'これは前回の合意内容として最初に確認された内容で、今回は単価引き下げのほうが見送りに変更されている。', 'a73f9251c8839672') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('e30344079e', 2, '単価は予定通り3％引き下げられ、納期は4週間のままとなった。', 'stated_by_wrong_speaker', '単価が予定通り下がるというのは営業部の担当者Bの発言だが、Aがすぐに否定しており、納期が4週間に戻るとは誰も言っていない。', '3e8d4820c6eb17b7') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;
insert into item_options (item_id, position, text, role, why, clip_id) values ('e30344079e', 3, '単価の引き下げは見送られたが、納期短縮の2週間は維持された。', 'correct', '営業部の担当者Aが材料費高騰で単価引き下げを見送ると明言し、納期短縮の2週間はそのまま進めると最後に述べている。', '3954a5b9d72a7adb') on conflict (item_id, position) do update set text = excluded.text, role = excluded.role, why = excluded.why, clip_id = excluded.clip_id;

